#!/bin/sh -e
# NAME=Array configurator
# DESCRIPTION=It is not a real test. Simply, it can create specified array configuration on disk controller with hard drives. Currently it can create only clear, optimal and passthrough disk configurations (related to einarc).
# DESTROYS_HDD=true
# IS_INTERACTIVE=false
# POWEROFF_DURING_TEST=false
# VERSION=0.1
# TAGS=hdd
# DEPENDS=HDD,Disk Controller
# VAR=CONFIGURATION:string:optimal:Configuration to pass to einarc
# VAR=DISK_GROUP_SIZE:int:8:Number of disks per group for testing (for passthrough configuration)
# VAR=DISK_GROUP_NUMBER:int:1:Number of disk group (for passthrough configuration)

# !!! Untested development version !!!

. /usr/share/inquisitor/functions-test

[ "$CONFIGURATION" = "passthrough" ] && PASSTHROUGH_ARGS="$DISK_GROUP_SIZE $DISK_GROUP_NUMBER" || PASSTHROUGH_ARGS=""

raid-wizard-$CONFIGURATION $PASSTHROUGH_ARGS || test_failed

test_succeeded
