#!/bin/sh -ef
# NAME=Bonnie
# DESCRIPTION=Bonnie HDD performance benchmark
# DESTROYS_HDD=true
# POWEROFF_DURING_TEST=false
# VERSION=0.1
# TAGS=benchmark,hdd

. /usr/share/inquisitor/functions-test

RESULT_FILE=`mktemp`
SCRATCH_DIRECTORY=`mktemp -d`

# Cleanup
exit_handler()
{
	local rc=$?
	trap - EXIT

	if [ -f "$RESULT_FILE" ]; then
		rm -fr "$RESULT_FILE"
	fi
	if [ -d "$SCRATCH_DIRECTORY" ]; then
		umount -f $SCRATCH_DIRECTORY
		rmdir $SCRATCH_DIRECTORY
	fi
	exit $rc
}
trap exit_handler HUP PIPE INT QUIT TERM EXIT

perform_benchmark()
{
	DRIVE=$1

	mke2fs -m0 -F $DRIVE >$DEBUG_TTY 2>&1
	mount $DRIVE $SCRATCH_DIRECTORY

	bonnie++ -u root -d $SCRATCH_DIRECTORY -s $TEST_FILE_SIZE \
		-n 1 -m benchmark > ${RESULT_FILE} 2>&1
	
	benchmark_submit_float "HDD $DRIVE output char speed" \
	`sed -n '$p' < ${RESULT_FILE} | awk -F, '{print $3}'`

	benchmark_submit_float "HDD $DRIVE output char CPU load" \
	`sed -n '$p' < ${RESULT_FILE} | awk -F, '{print $4}'`

	benchmark_submit_float "HDD $DRIVE output block speed" \
	`sed -n '$p' < ${RESULT_FILE} | awk -F, '{print $5}'`

	benchmark_submit_float "HDD $DRIVE output block CPU load" \
	`sed -n '$p' < ${RESULT_FILE} | awk -F, '{print $6}'`

	benchmark_submit_float "HDD $DRIVE rewrite speed" \
	`sed -n '$p' < ${RESULT_FILE} | awk -F, '{print $7}'`

	benchmark_submit_float "HDD $DRIVE rewrite CPU load" \
	`sed -n '$p' < ${RESULT_FILE} | awk -F, '{print $8}'`

	benchmark_submit_float "HDD $DRIVE input char speed" \
	`sed -n '$p' < ${RESULT_FILE} | awk -F, '{print $9}'`

	benchmark_submit_float "HDD $DRIVE input char CPU load" \
	`sed -n '$p' < ${RESULT_FILE} | awk -F, '{print $10}'`

	umount $SCRATCH_DIRECTORY
}

TOTAL_MEMORY=$(( `grep MemTotal /proc/meminfo | awk '{print $2}'` / 1024 ))
TEST_FILE_SIZE=$(($TOTAL_MEMORY * 2))

for BLOCK_DEV in `get_harddrives_list`; do
	echo -n "HDD $BLOCK_DEV"
	perform_benchmark $BLOCK_DEV
	echo_success
done
