#!/bin/sh -ef
# client/test/bytemark - A part of Inquisitor project
# Copyright (C) 2004-2008 by Iquisitor team 
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# NAME=BYTEmark
# DESCRIPTION=BYTEmark native mode benchmark
# DESTROYS_HDD=false
# POWEROFF_DURING_TEST=false
# VERSION=0.1
# TAGS=benchmark,cpu,memory,ram
# DEPENDS=CPU,Memory,Mainboard

. /usr/share/inquisitor/functions-test

exit_handler()
{
	[ -d "$WORKING_DIR" ] && rm -rf "$WORKING_DIR"
}

WORKING_DIR=`mktemp -d`

echo -n "Running BYTEmark benchmark..."
cd $WORKING_DIR
cp $SHARE_DIR/test/additional/NNET.DAT .
cp $SHARE_DIR/test/additional/COM.DAT .
nbench > result

benchmark_submit_float "Numeric sort" `grep "NUMERIC SORT" < result | \
	awk '{print $4}'`
benchmark_submit_float "String sort" `grep "STRING SORT" < result | \
	awk '{print $4}'`
benchmark_submit_float "Bitfield" `grep "BITFIELD" < result | \
	awk '{print $3}'`
benchmark_submit_float "FP emulation" `grep "FP EMULATION" < result | \
	awk '{print $4}'`
benchmark_submit_float "Fourier" `grep "FOURIER" < result | \
	awk '{print $3}'`
benchmark_submit_float "Assignment" `grep "ASSIGNMENT" < result | \
	awk '{print $3}'`
benchmark_submit_float "IDEA" `grep "IDEA" < result | \
	awk '{print $3}'`
benchmark_submit_float "Huffman" `grep "HUFFMAN" < result | \
	awk '{print $3}'`
benchmark_submit_float "Neural net" `grep "NEURAL NET" < result | \
	awk '{print $4}'`
benchmark_submit_float "Lu decomposition" `grep "LU DECOMPOSITION" < result | \
	awk '{print $4}'`

benchmark_submit_float "Integer Index" `grep "INTEGER INDEX" < result | \
	awk '{print $4}' | sed -n '2p'`
benchmark_submit_float "Floating-poing Index" \
	`grep "FLOATING-POINT INDEX" < result | awk '{print $3}' | sed -n '2p'`
benchmark_submit_float "Memory Index" `grep "MEMORY INDEX" < result | \
	awk '{print $4}'`

cd $HOME
echo_success

test_succeeded
