#!/bin/sh -ef
# NAME=DB to Detects comparison
# DESCRIPTION=Stops testing until comparison has been completed on application server
# DESTROYS_HDD=false
# IS_INTERACTIVE=false
# POWEROFF_DURING_TEST=false
# VERSION=0.1
# TAGS=

. /usr/share/inquisitor/functions-test

print_green_message "Please refer to the web interface to confirm detected hardware placement"

[ "`wait-string`" == "OK" ] && test_succeeded || test_failed 
