#!/bin/sh -ef
# NAME=DB to Detects comparison
# DESCRIPTION=Pauses testing until comparison has been completed on the application server.
# DESTROYS_HDD=false
# IS_INTERACTIVE=false
# POWEROFF_DURING_TEST=false
# VERSION=0.1
# DEPENDS=BMC,CPU,Chassis,Disk Controller,Floppy,HDD,Mainboard,Memory,NIC,OSD,Platform,USB,Video
# TAGS=

. /usr/share/inquisitor/functions-test

# Check if we have already passed this stage
check_audit && test_succeeded || true

print_green_message "Please refer to the web interface to confirm detected hardware placement"

require_attention
if [ "`wait-string`" == "OK" ]; then
	dismiss_attention
	test_succeeded
else
	dismiss_attention
	test_failed 
fi
