#!/bin/sh -ef
# client/test/dhrystone - A part of Inquisitor project
# Copyright (C) 2004-2008 by Iquisitor team 
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# NAME=Dhrystone
# DESCRIPTION=Dhrystone integer calculations benchmark
# DESTROYS_HDD=false
# POWEROFF_DURING_TEST=false
# VERSION=0.1
# TAGS=benchmark,cpu
# DEPENDS=CPU
# VAR=DURATION:int:30:Benchmark duration (sec)

. /usr/share/inquisitor/functions-test

exit_handler()
{
	[ -f "$RESULT_FILE" ] && rm -f $RESULT_FILE
}

CPU_QUANTITY=`grep processor /proc/cpuinfo | wc -l`

for i in `seq 0 $(($CPU_QUANTITY - 1))`; do
	echo -n "Dhrystone on core $i"
	result=`taskset -c $i dhrystone $DURATION 2>&1 | awk '{print $1}'`
	echo_success
	benchmark_submit_float "Core $i loops" "$result"
done

test_succeeded
