#!/bin/sh -ef
# NAME=FDD read/write
# DESCRIPTION=Floppy drive read/write test
# DESTROYS_HDD=false
# IS_INTERACTIVE=true
# POWEROFF_DURING_TEST=false
# VERSION=0.1
# TAGS=fdd
# VAR=FLOPPY_SIZE:int:1440:Size of testing floppy, KiB

. /usr/share/inquisitor/functions-test

TEST_IMAGE=`mktemp`

# Cleanup
exit_handler()
{
	local rc=$?
	trap - EXIT

	if [ -f "$TEST_IMAGE" ]; then
		rm -f $TEST_IMAGE
	fi
	if [ -f "$TEST_IMAGE"_fd ]; then
		rm -f "$TEST_IMAGE"_fd
	fi
	exit $rc
}
trap exit_handler HUP PIPE INT QUIT TERM EXIT

generate_test_image()
{
	if dd if=/dev/urandom of=$TEST_IMAGE bs=1024 count=$FLOPPY_SIZE; then
		true
	else
		test_failed "Unable to create test image"
		FDD_QUANTITY=0 #to not to start interactive cycles
	fi
}

test_fdd()
{
	dd if=$TEST_IMAGE of=/dev/fd$1 >/dev/null 2>&1
	floppycontrol -f -d /dev/fd$1 >/dev/null 2>&1
	dd if=/dev/fd$1 of="$TEST_IMAGE"_fd bs=1024 count=$FLOPPY_SIZE >/dev/null 2>&1
	diff "$TEST_IMAGE"_fd $TEST_IMAGE >/dev/null 2>&1 || return 1
	return 0
}

interactive()
{
	local fdd=$1
	local non_passed=1

	while ( [ "$non_passed" -eq 1 ] ); do
		print_green_message "Drive /dev/fd${fdd}:"
		print_green_message "Either press y and insert floppy for testing, or n if you want to finish test: "
		read choice

		if [ "$choice" = "n" ]; then
			test_failed "User cancelled test for $fdd"
			break
		fi

		test_fdd $(( $fdd - 1 ))

		if $(( $? == 0 )); then
			print_green_message "Drive test passed"
			test_progress $fdd $FDD_QUANTITY
			non_passed=0
		else
			print_red_message "Drive test failed!"
		fi
	done
}

FDD_QUANTITY=`ls /dev/* | sed 's/\/dev\///g' | grep '^fd[0-9]*$' | wc -l`
[ "$FDD_QUANTITY" -eq 0 ] && return
generate_test_image

for i in `seq 1 $FDD_QUANTITY`; do
	interactive $i
done

test_succeeded
