#!/bin/sh
# NAME=fdd
# DESCRIPTION=Floppy drive test
# DESTROYS_HDD=N
# IS_INTERACTIVE=Y
# POWEROFF_DURING_TEST=N
# VERSION=0.1
# VAR=FDD_SIZE:int:1440:Size of testing floppy, KiB

. /usr/share/inquisitor/functions-test

FDD_TEST_IMAGE=`mktemp`

detect_fdd_quantity()
{
	FDD_QUANTITY=`ls /dev/* | sed 's/\/dev\///g' | grep '^fd[0-9]*$' | wc -l`
}

generate_test_image()
{
	if dd if=/dev/urandom of=$FDD_TEST_IMAGE bs=1024 count=$FDD_SIZE; then
		true
	else
		test_failed
		FDD_QUANTITY=0 #to not to start interactive cycles
	fi
}

remove_test_image()
{
	rm -f $FDD_TEST_IMAGE
	rm -f "$FDD_TEST_IMAGE"_fd
}

test_fdd()
{
	dd if=$FDD_TEST_IMAGE of=/dev/fd$1 >/dev/null 2>&1
	floppycontrol -f -d /dev/fd$1 >/dev/null 2>&1
	dd if=/dev/fd$1 of="$FDD_TEST_IMAGE"_fd bs=1024 count=$FDD_SIZE >/dev/null 2>&1
	diff "$FDD_TEST_IMAGE"_fd $FDD_TEST_IMAGE >/dev/null 2>&1 || return 1
	return 0
}

interactive()
{
	FDD=$1
	NON_PASSED=1

	while ( [ $NON_PASSED ] ); do
		echo -n "Drive ${FDD}:Either press Y and insert floppy for testing, or N if you want to finish test: "
		read choice

		if [ "$choice" = "N" ]; then
			test_failed
			break
		fi

		test_fdd $[$FDD - 1]

		if (( $? == 0 )); then
			echo "Drive test passed"
			test_progress $FDD $FDD_QUANTITY
			NON_PASSED=0
		else
			echo "Drive test failed!"
		fi
	done
}

detect_fdd_quantity
[ "$FDD_QUANTITY" -eq 0 ] && return
generate_test_image

test_started $FDD_QUANTITY
for i in `seq 1 $FDD_QUANTITY`; do
	interactive $i
done

remove_test_image
test_succeeded
