#!/bin/sh -ef
# NAME=Flash disk
# DESCRIPTION=Flash disk badblocks test
# DESTROYS_HDD=true
# IS_INTERACTIVE=false
# POWEROFF_DURING_TEST=false
# VERSION=0.1
# TAGS=hdd,flash
# VAR=SIZE_LIMIT:int:2048:Everything that is less than this amount (MiB) is an IDE flash

. /usr/share/inquisitor/functions-test

SIZE_LIMIT=$(( $SIZE_LIMIT * 1024 * 2 ))
DEVICE_LIST_FILE=`mktemp`
BADBLOCKS_COMMAND="badblocks -svw"

load_ide_devices()
{
	rmmod ata_generic || true
	rmmod ata_piix || true
	rmmod libata || true
	sleep 10
	modprobe ide-generic || true
	sleep 10
}

detect_flash_devices()
{
	FLASH_QUANTITY=0

	for i in /sys/block/*; do
		DEVICE=`basename $i`
		echo $DEVICE | egrep -q '[0-9]' && continue
		grep -q "$DEVICE" /proc/partitions || continue

		SIZE=`cat /sys/block/$DEVICE/size`
		if [ "$SIZE" -lt "$SIZE_LIMIT" ]; then
			echo $DEVICE >> $DEVICE_LIST_FILE
			FLASH_QUANTITY=$[ $FLASH_QUANTITY + 1 ]
		fi
	done
}

flash_test()
{
	TESTED_DEVICES=1
	for i in `cat $DEVICE_LIST_FILE`; do
		$BADBLOCKS_COMMAND /dev/$i >/dev/null 2>&1 || test_failed
		test_progress $TESTED_DEVICES $FLASH_QUANTITY
		TESTED_DEVICES=$[ $TESTED_DEVICES + 1 ]
	done
}

load_ide_devices
detect_flash_devices

if [ "$FLASH_QUANTITY" -gt "0" ]; then
	test_started $FLASH_QUANTITY
	flash_test
	test_succeeded
fi
