#!/bin/sh -ef
# NAME=USB GPRS modem signal level
# DESCRIPTION=Measure level of signal, received by GPRS modem, connected using USB
# DESTROYS_HDD=false
# IS_INTERACTIVE=false
# POWEROFF_DURING_TEST=false
# VERSION=0.1
# TAGS=usb,gprs
# VAR=DEV:string:/dev/ttyUSB0:Name of device to test
# VAR=CHAT_TIMEOUT:int:5:Timeout for waiting for answer

. /usr/share/inquisitor/functions-test

exit_handler()
{
	[ -f "$TMP_DIR/level" ] && rm -f "$TMP_DIR/level"
	[ -d "$TMP_DIR" ] && rmdir "$TMP_DIR"
}

echo -n 'Resetting modem'
stty 115200 -F $DEV
sleep 1
echo_success

TMP_DIR=`mktemp -d`
echo 'Getting signal level'
while true; do
	chat -t $CHAT_TIMEOUT -Vs '' AT OK-AT-OK AT+CSQ OK <$DEV >$DEV 2>$TMP_DIR/level || test_failed 'Getting signal level'
	LEVEL=`sed -ne '/^\+CSQ: / { s/^\+CSQ: //; p; }' <$TMP_DIR/level`
	echo "GPRS level: $LEVEL"
	echo -n 'Press ENTER to retry, enter "y" to complete the test: '
	read L
	[ "$L" = y ] && break || :
done
echo_success

benchmark_submit_float 'GPRS level' "$LEVEL"

exit_handler
test_succeeded
