#!/bin/sh -ef
# client/test/gprs-modem-level - A part of Inquisitor project
# Copyright (C) 2004-2008 by Iquisitor team 
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# NAME=USB GPRS modem signal level
# DESCRIPTION=Measure signal level, received by GPRS modem, connected via USB
# DESTROYS_HDD=false
# IS_INTERACTIVE=false
# POWEROFF_DURING_TEST=false
# VERSION=0.1
# TAGS=usb,gprs
# VAR=DEV:string:/dev/ttyUSB0:Name of device to test
# VAR=CHAT_TIMEOUT:int:5:Timeout for waiting for answer

. /usr/share/inquisitor/functions-test

exit_handler()
{
	[ -f "$TMP_DIR/level" ] && rm -f "$TMP_DIR/level"
	[ -d "$TMP_DIR" ] && rmdir "$TMP_DIR"
}

echo -n 'Resetting modem'
stty 115200 -F $DEV
sleep 1
echo_success

TMP_DIR=`mktemp -d`
echo 'Getting signal level'
while true; do
	chat -t $CHAT_TIMEOUT -Vs '' AT OK-AT-OK AT+CSQ OK <$DEV >$DEV \
		2>$TMP_DIR/level || test_failed 'Getting signal level'
	LEVEL=`sed -ne '/^\+CSQ: / { s/^\+CSQ: //; p; }' <$TMP_DIR/level`
	echo "GPRS level: $LEVEL"
	echo -n 'Press ENTER to retry, enter "y" to complete the test: '
	read L
	[ "$L" = y ] && break || :
done
echo_success

benchmark_submit_float 'GPRS level' "$LEVEL"

test_succeeded
