#!/bin/sh

for DISK in `storagescan | grep Disk | cut -f1`; do
	echo Benchmarking $DISK

	echo -n >hddbench1.log

	for I in `seq 1 10`; do
		hdparm -t /dev/$DISK | grep '^ Timing' >>hddbench1.log
	done

	echo Disk: $DISK >>~/hddbench.log
	cat ~/hddbench1.log >>~/hddbench.log
done

publish ~/hddbench.log

test_ok_file
