#!/bin/sh
# NAME=Memory
# DESCRIPTION=Memory test
# DESTROYS_HDD=N
# IS_INTERACTIVE=N
# POWEROFF_DURING_TEST=N

. /usr/share/inquisitor/functions-test

TOTAL_MEMORY=$[(`cat /proc/meminfo | grep MemTotal | awk '{print $2}'` / 1024)-16]

memtester $TOTAL_MEMORY 1 > memtest.log

publish_log memtest

test_success
