#!/bin/sh -ef
# NAME=Memory
# DESCRIPTION=Memory test
# DESTROYS_HDD=false
# IS_INTERACTIVE=false
# POWEROFF_DURING_TEST=false
# VERSION=0.1
# TAGS=ram,memory
# VAR=TEST_LOOPS:int:3:Number of testing loops
# VAR=LOGTIME:int:120:Time between progress updates, sec

. /usr/share/inquisitor/functions-test

#Temporary disabled because of broken oom_killer
#TOTAL_MEMORY=$(( `grep MemTotal /proc/meminfo | awk '{print $2}'` / 1024 ))

TOTAL_MEMORY=$(( (`grep MemTotal /proc/meminfo | awk '{print $2}'`) / 1024 - 256 ))
TOTAL_SUBSTAGES=$(( 16 * $TEST_LOOPS ))
COMPLETED_SUBSTAGES=0
MEMORY_LOG=`mktemp`

# Cleanup
exit_handler()
{
	local rc=$?
	trap - EXIT

	if [ -d /proc/$MEMTEST_PID ] ; then
		kill $MEMTEST_PID
	fi

	exit $rc
}
trap exit_handler HUP PIPE INT QUIT TERM EXIT

turnoff_oom_killer()
{
	sysctl vm.overcommit_memory=2
	sysctl vm.overcommit_ratio=1
}

turnon_oom_killer()
{
	sysctl vm.overcommit_memory=0
	sysctl vm.overcommit_ratio=50
}

#turnoff_oom_killer

memtester $TOTAL_MEMORY $TEST_LOOPS > $MEMORY_LOG &
MEMTEST_PID=$!

while true ; do
	sleep $LOGTIME
	COMPLETED_SUBSTAGES=`sed '{:loop g; n; s/^Loop\|Done/\0/; T loop; g; \
		b nloop; :nloop n; s/^Loop\|Done/\0/; T nloop; g; b nloop; }' \
		< $MEMORY_LOG | grep -v '^$' | wc -l`
	if [ -d /proc/$MEMTEST_PID ] ; then
		test_progress $COMPLETED_SUBSTAGES $TOTAL_SUBSTAGES
	else
		if [ "$COMPLETED_SUBSTAGES" -eq "$TOTAL_SUBSTAGES" ] ; then
			test_succeeded
			#turnon_oom_killer
			break
		else
			if grep -q "FAILURE: possible bad address line"; then
				possible_bad=`grep "FAILURE: possible bad address line" $MEMORY_LOG | awk '{print $NF}'`
				print_red_message "Possible bad address line: $possible_bad"
				test_failed $possible_bad
				#turnon_oom_killer
			else
				test_failed
				#turnon_oom_killer
			fi

			break
		fi
	fi
done
