#!/bin/sh -ef
# NAME=Mencoder
# DESCRIPTION=Mencoder encoding time benchmark
# DESTROYS_HDD=false
# POWEROFF_DURING_TEST=false
# VERSION=0.1
# TAGS=benchmark,cpu,stress
# VAR=ENCODE_OPTIONS:string:-ovc lavc -lavcopts vcodec=mpeg4 -oac mp3lame -lameopts vbr=3:Encoding options
# VAR=FILE_TO_ENCODE:string:/usr/share/inquisitor/movie.avi:Path to file need to be encoded

. /usr/share/inquisitor/functions-test

RESULT_FILE=`mktemp`

# Cleanup
exit_handler()
{
	local rc=$?
	trap - EXIT

	if [ -f "$RESULT_FILE" ]; then
		rm -f "$RESULT_FILE"
	fi
	exit $rc
}
trap exit_handler HUP PIPE INT QUIT TERM EXIT

time -o $RESULT_FILE mencoder $ENCODE_OPTIONS \
	-o $DEBUG_TTY $FILE_TO_ENCODE

benchmark_submit_float "User time" \
`sed -n "s/user//;1p" < $RESULT_FILE | awk '{print $1}'`

benchmark_submit_float "System time" \
`sed -n "s/system//;1p" < $RESULT_FILE | awk '{print $1}'`
