#!/bin/sh -ef
# client/test/mencoder - A part of Inquisitor project
# Copyright (C) 2004-2008 by Iquisitor team 
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# NAME=Mencoder
# DESCRIPTION=Mencoder encoding time benchmark
# DESTROYS_HDD=false
# POWEROFF_DURING_TEST=false
# VERSION=0.1
# TAGS=benchmark,cpu,stress
# DEPENDS=CPU,Memory,Mainboard
# VAR=ENCODE_OPTIONS:string:-ovc lavc -lavcopts vcodec=mpeg4 -oac mp3lame -lameopts vbr=3:Encoding options
# VAR=FILE_TO_ENCODE:string:/usr/share/inquisitor/movie.avi:Path to file need to be encoded

. /usr/share/inquisitor/functions-test

exit_handler()
{
	[ -f "$RESULT_FILE" ] && rm -f "$RESULT_FILE"
}

RESULT_FILE=`mktemp`

time -o $RESULT_FILE mencoder $ENCODE_OPTIONS \
	-o $DEBUG_TTY $FILE_TO_ENCODE

benchmark_submit_float "User time" \
`sed -n "s/user//;1p" < $RESULT_FILE | awk '{print $1}'`

benchmark_submit_float "System time" \
`sed -n "s/system//;1p" < $RESULT_FILE | awk '{print $1}'`

test_succeeded
