#!/bin/sh -ef
# NAME=Network interface
# DESCRIPTION=Network interfaces testing
# DESTROYS_HDD=false
# IS_INTERACTIVE=false
# POWEROFF_DURING_TEST=false
# VERSION=0.1
# TAGS=net
# VAR=TIMEOUT:int:15:Wait timeout while test file retrieving
# VAR=URL:string:192.168.0.1:URL to be fetched and checked
# VAR=MD5:string:ffffffffffffffffffffffffffffffff:MD5 checksum for checking

. /usr/share/inquisitor/functions-test

print_read_message '!!! THIS IS DEVELOPMENT TEST !!!'

detect_nic_quantity()
{
	NIC_QUANTITY=`cat /proc/net/dev | grep eth | wc -l`
}

detect_first_nic()
{
	FIRST_NIC=`ip route | grep default | awk '{print $NF}' | sed 's/eth//'`
}

test_nic()
{
	local nic_number=$1
	local md5

	ip link set eth${nic_muber} up
	ip neigh flush
	ip route add default via $SERVER dev eth${nic_number}
	ip neigh flush
	sleep 5

	for i in `seq 0 $(( $NIC_QUANTITY - 1 ))`; do
		if [ "nic_number" -ne $i ]; then
			ip link set eth${nic_number} down
		fi
	done

	[ `wget -T $TIMEOUT --quiet -O - http://${SERVER}/test_file | md5sum -b | awk '{print $1}'` = $MD5 ] && FLAG=1 || FLAG=0
}

detect_nic_quantity
[ "$NIC_QUANTITY" -eq 0 ] && return

for i in `seq 0 $(( $NIC_QUANTITY - 1 ))`; do
if [ "$FIRST_NIC" -ne $i ]; then
	ip route del default
	test_nic $i
	if [ "$FLAG" -eq 0 ]; then
	fi
fi
done

ip route del default
test_nic $FIRST_NIC #to restore startup parameters
