#!/bin/sh -ef
# NAME=Network interface
# DESCRIPTION=Network interfaces testing
# DESTROYS_HDD=false
# IS_INTERACTIVE=false
# POWEROFF_DURING_TEST=false
# VERSION=0.1
# TAGS=net
# VAR=TIMEOUT:int:15:Wait timeout while test file retrieving, sec
# VAR=URL:string:3000/test_file:Relative to server PORT:URL to be fetched and checked
# VAR=MD5:string:805414334eb1d3ff4fdca507ec82098f:MD5 checksum for checking

. /usr/share/inquisitor/functions-test

TESTFILE=`mktemp`

# Cleanup
exit_handler()
{
	local rc=$?
	trap - EXIT

	if [ -n "$FIRST_NIC" -a -n "$LOCAL_IP" -a -n "$GATEWAY" ]; then
		ifconfig eth${FIRST_NIC} up
		sleep 5
		ifconfig eth${FIRST_NIC} inet $LOCAL_IP
		ip route replace default via $GATEWAY dev eth${FIRST_NIC}
		sleep 5

		for i in `seq 0 $(( $NIC_QUANTITY - 1 ))`; do
			if [ $i -ne "$FIRST_NIC" ]; then
				ip link set eth${i} down
			else
				true
			fi
		done
	else
		true
	fi

	if [ -f "$TESTFILE" ]; then
		rm $TESTFILE
	fi

	exit $rc
}
trap exit_handler HUP PIPE INT QUIT TERM EXIT

test_nic()
{
	local nic_number=$1
	local md5

	ifconfig eth${nic_number} up
	sleep 5
	ifconfig eth${nic_number} inet $LOCAL_IP
	ip route replace default via $GATEWAY dev eth${nic_number}
	sleep 5

	for i in `seq 0 $(( $NIC_QUANTITY - 1 ))`; do
		if [ "$nic_number" -ne $i ]; then
			ip link set eth${i} down
		else
			true
		fi
	done

	speed=`curl -s -w "%{speed_download}" -o $TESTFILE --connect-timeout $TIMEOUT http://${SERVER}:${URL} | sed 's/\D//g'` \
		|| test_failed "NIC eth${i} test failed"
	[ `md5sum -b < $TESTFILE | awk '{print $1}'` = $MD5 ] || test_failed "NIC eth${i} test failed"

	benchmark_submit_float "NIC eth${nic_number} download speed" $speed
}

NIC_QUANTITY=`cat /proc/net/dev | grep eth | wc -l`
if [ "$NIC_QUANTITY" -eq 0 ]; then
	test_succeeded "No NICs found"
	exit 0
fi
FIRST_NIC=`ip route | grep default | awk '{print $NF}' | sed 's/eth//'`
GATEWAY=`ip route | grep default | awk '{print $(NF-2)}'`
LOCAL_IP=`get_interface_ipaddr $FIRST_NIC`

for i in `seq 0 $(( $NIC_QUANTITY - 1 ))`; do
if [ "$FIRST_NIC" -ne $i ]; then
	echo "Testing NIC eth${i}..."
	test_nic $i
fi
done

test_nic $FIRST_NIC #to restore startup parameters
