#!/bin/sh
# NAME=odd_write
# DESCRIPTION=Optical Disc Drive write test
# DESTROYS_HDD=N
# IS_INTERACTIVE=Y
# POWEROFF_DURING_TEST=N
# VERSION=0.1
# VAR=ODD_TEST_IMAGE:str:/usr/share/inquisitor/testimage.iso:Default image for comparison
# VAR=ODD_TEST_IMAGE_BLOCKS:int:332800:This images size in blocks (2048 bytes each)
# VAR=ODD_TEST_IMAGE_MD5:str:ffffffffffffffffffffffffffffffff:Test image MD5 hash
# VAR=ODD_WRITE_SPEED:int:10:Default write speed if it won't detect

. /usr/share/inquisitor/functions-test

load_kernel_modules()
{
	modprobe ide-cd || true
	sleep 5
}

detect_odd_quantity()
{
	ODD_QUANTITY=`hal-find-by-capability --capability storage.cdrom | wc -l`
}

test_read()
{
	local odd=$1
	local hash

	hash=`readcd -v dev=$odd f=- sectors=0-$ODD_TEST_IMAGE_BLOCKS | md5sum -b | awk '{print $1}'`
	[ -z "$hash" ] && {hash=`dd if=$odd bs=2048 count=$ODD_TEST_IMAGE_BLOCKS | md5sm -b | awk '{print $1}'`}

	[ $hash = $ODD_TEST_IMAGE_MD5 ] && FLAG=1 || FLAG=0
}

test_write()
{
	local odd=$1

	check_media_existence $odd
	detect_maxspeed $odd
	blank_if_needed $odd $SPEED

	echo "Writing..."
	cdrecord dev=$odd driveropts=burnfree speed=$SPEED \
		-data $ODD_TEST_IMAGE >/dev/null && FLAG=1 || FLAG=0
	echo "writing done"
}

check_media_existence()
{
	local odd=$1

	if cdrecord dev=$odd -atip | grep -q 'Is erasable'; then
		echo 'Rewritable media already inserted, not ejecting'
	else
		echo "Insert writable media..."
		eject
	fi
}

detect_maxspeed()
{
	local odd=$1

	SPEED=`cdrecord dev=$odd -atip | \
		sed -ne '/speed high/ s/^.*speed high: \(.*\)$/\1/ p' | head -n 1`
	[ -z "$SPEED" ] && SPEED=$ODD_WRITE_SPEED || true
}

blank_if_needed()
{
	local odd=$1
	local speed=$2

	if cdrecord dev=$odd -atip | grep -q 'Is erasable'; then
		echo "Blanking..."
		cdrecord dev=$odd speed=$speed blank=fast >/dev/null 2>&1
		echo "done blanking"
	else
		echo 'Non rewritable media. Skipping blanking...'
	fi
}

interactive()
{
	local odd=$1
	local non_passed=1

	while ( [ "$non_passed" -eq 1 ] ); do
		echo ""
		echo -n "Drive $[ $TESTED_QUANTITY + 1]:"
		echo -n "Either press Y and insert media for testing, or N if you want to finish test: "
		read choice

		if [ "$choice" = "N" ]; then
			test_failed
			break
		fi

		FLAG=0
		test_write $odd

		if [ "$FLAG" -eq 1 ]; then
			echo "Write stage passed, performing read test..."

			FLAG=0
			test_read $odd

			if [ "$FLAG" -eq 1 ]; then
				echo "Drive test passed"
				TESTED_QUANTITY=$[ $TESTED_QUANTITY + 1 ]
				test_progress $TESTED_QUANTITY $ODD_QUANTITY
				non_passed=0
			else
				echo "Drive test failed!"
			fi
		else
			echo "Write stage failed!"
		fi
	done
}

load_kernel_modules
detect_odd_quantity
[ "$ODD_QUANTITY" -eq 0 ] && return
TESTED_QUANTITY=0
test_started $ODD_QUANTITY

for i in `hal-find-by-capability --capability storage.cdrom`; do
	interactive `hal-device $i | grep access_control.file | \
		awk '{print $3}' | sed "s/'//g"`
done

test_succeeded
