#!/bin/sh -e
# NAME=openssl-speed
# DESCRIPTION=This benchmark measures different OpenSSL algorithm's speed with different block sizes (for symmetric algorithms) or key sizes for signing and verifying.
# DESTROYS_HDD=false
# IS_INTERACTIVE=false
# POWEROFF_DURING_TEST=false
# VERSION=0.1
# TAGS=cpu,benchmark
# DEPENDS=CPU

. _inq-config-global; . $SHARE_DIR/functions-test

OPENSSL_LOG=`openssl speed -mr 2>$DEBUG_TTY` || test_failed "openssl failed"

printf "$OPENSSL_LOG" | while read line; do
	case "`echo $line | sed -n 's/^+\([^:]*\):.*$/\1/p'`" in
	H)
		blocksizes=`echo $line | sed 's/^+H://'`
		;;
	F)
		for i in `seq 4 8`; do
			blocksize=`echo "$blocksizes" | awk -F: '{print $'$(( $i - 3 ))'}'`
			benchmarking=`echo "$line" | awk -F: '{print $3}'`
			performance=`echo "$line" | awk -F: '{print $'$i'}'`
			benchmark_submit_float "$benchmarking x $blocksize" "$performance" ""
		done
		;;
	*)
		echo "$line" | grep -q "^.F2" && algorithm="rsa" || algorithm="dsa"
		blocksize=`echo "$line" | awk -F: '{print $3}'`
		sign=`echo "$line" | awk -F: '{print $4}'`
		verify=`echo "$line" | awk -F: '{print $5}'`
		benchmark_submit_float "$algorithm x $blocksize sign" "$sign" "sec"
		benchmark_submit_float "$algorithm x $blocksize verify" "$verify" "sec"
		;;
	esac
done
test_succeeded
