#!/bin/sh -e
# NAME=openssl-speed
# DESCRIPTION=This benchmark measures different OpenSSL algorithm's speed with different block sizes (for symmetric algorithms) or key sizes for signing and verifying.
# DESTROYS_HDD=false
# IS_INTERACTIVE=false
# POWEROFF_DURING_TEST=false
# VERSION=0.1
# TAGS=cpu,benchmark
# DEPENDS=CPU

. _inq-config-global; . $SHARE_DIR/functions-test

exit_handler()
{
	[ -f "$OPENSSL_LOG" ] && rm $OPENSSL_LOG
}

OPENSSL_LOG=`mktemp`

openssl speed >$OPENSSL_LOG 2>&1 || test_failed "openssl failed"

cat $OPENSSL_LOG | while read line; do
	# Algorithm, blocksize, blocks, time
	result=`echo $line | sed -n 's/^Doing \(.*\) for [0-9]*s on \([0-9]*\) size blocks: \([0-9]*\) .*s in \([0-9\.]*\)s$/\1:\2:\3:\4/p'`
	if [ -n "$result" ]; then
		algorithm=`echo $result | awk -F: '{print $1}'`
		blocksize=`echo $result | awk -F: '{print $2}'`
		blocks=`echo $result | awk -F: '{print $3}'`
		time=`echo $result | awk -F: '{print $4}'`
		
		benchmarking="$algorithm x $blocksize"
		performance=`perl -e "print $blocks * $blocksize / $time"`
	else
		# Try another pattern for sign/verify
		# Blocksize, algorithm, blocks, time
		result=`echo $line | sed -n "s/^Doing \(.*\) bit \(.*\)'s for [0-9]*s: \([0-9]*\) .* \([0-9\.]*\)s$/\1:\2:\3:\4/p"`
		algorithm=`echo $result | awk -F: '{print $2}'`
		blocksize=`echo $result | awk -F: '{print $1}'`
		blocks=`echo $result | awk -F: '{print $3}'`
		time=`echo $result | awk -F: '{print $4}'`

		benchmarking="$algorithm $blocksize bit"
		performance=`perl -e "print $blocks / $time" 2>/dev/null`
	fi
	[ -z "$result" ] || benchmark_submit_float "$benchmarking" "$performance" ""

done
test_succeeded
