#!/bin/sh -e
# NAME=Partimage
# DESCRIPTION=Actually this is not a real test. It can be used to write prepared raw disk image using Partimage utility.
# DESTROYS_HDD=true
# IS_INTERACTIVE=false
# POWEROFF_DURING_TEST=false
# VERSION=0.1
# TAGS=
# DEPENDS=HDD,Disk Controller
# VAR=IF:string:raw_disk_image:Absolute of relative path to source raw disk image to be written
# VAR=OF:string:sda:Target device name that will be overwritten
# VAR=BLOCKSIZE:int:1024:Blocksize, KiB
# VAR=SKIP:int:0:Number of blocks to skip
# VAR=COUNT:int:1024:Number of blocks to be written

. /usr/share/inquisitor/functions-test

cd $SHARE_DIR/firmwares

# Some protection from fools to produce test fail comments
[ -e "$SOURCE" ] || test_failed 'Source file does not exist'
[ -b "/dev/$TARGET" ] || test_failed 'Target device is not block device'

# Perform disk image restoring itself
partimage restore --batch /dev/"$TARGET" "$SOURCE" || test_failed 'Partimage failed'

test_succeeded
