#!/bin/sh -ef
# NAME=Stream
# DESCRIPTION=STREAM memory throughput benchmark
# DESTROYS_HDD=false
# POWEROFF_DURING_TEST=false
# VERSION=0.1
# TAGS=benchmark,ram,memory

. /usr/share/inquisitor/functions-test

echo "Copy operation..."
benchmark_submit_float "Memory Copy operation" `stream-mem | grep "^Copy" | awk '{print $2}'`
echo_success

echo "Scale operation..."
benchmark_submit_float "Memory Scale operation" `stream-mem | grep "^Scale" | awk '{print $2}'`
echo_success

echo "Add operation..."
benchmark_submit_float "Memory Add operation" `stream-mem | grep "^Add" | awk '{print $2}'`
echo_success

echo "Triad operation..."
benchmark_submit_float "Memory Triad operation" `stream-mem | grep "^Triad" | awk '{print $2}'`
echo_success
