#!/bin/sh
# NAME=Stress_array
# DESCRIPTION=Stress test array
# DESTROYS_HDD=Y
# IS_INTERACTIVE=N
# POWEROFF_DURING_TEST=N

. /usr/share/inquisitor/functions-test

raid-wizard-optimal || {
	publish_msg "Unable to set up an array"
	test_failure
}

sleep 10

DRIVES=`ls -1 /sys/block/ | grep -v '[0-9]$'`
DRIVES_NUM=`ls -1 /sys/block/ | grep -v '[0-9]$' | wc -l`
if [ "$DRIVES_NUM" -gt 0 ]; then
	TESTING_TIME=$[3600/$DRIVES_NUM]
else
	TESTING_TIME=1800
fi

echo "Arrays: $DRIVES"
echo "Testing time per array: $TESTING_TIME"

for I in $DRIVES; do
	echo Testing array $I

	export STRESS_BUILD_DEVICE="ram0"
	export STRESS_BUILD_TIMEOUT=10800
	export STRESS_BUILD_TARGET="rd"
	export STRESS_BUILD_LOGTIME=3600

	./additional/stress-build || {
		publish_msg "Array $I HDD test failed"
		test_failed
	}
done

test_success
