#!/bin/sh -ef
# client/test/stream - A part of Inquisitor project
# Copyright (C) 2004-2008 by Iquisitor team 
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# NAME=Stream
# DESCRIPTION=STREAM memory throughput benchmark
# DESTROYS_HDD=false
# POWEROFF_DURING_TEST=false
# VERSION=0.1
# TAGS=benchmark,ram,memory
# DEPENDS=Memory

. /usr/share/inquisitor/functions-test

echo -n "Copy operation..."
benchmark_submit_float "Memory Copy operation" `stream-mem | grep "^Copy" | \
	awk '{print $2}'`
echo_success

echo -n "Scale operation..."
benchmark_submit_float "Memory Scale operation" `stream-mem | grep "^Scale" | \
	awk '{print $2}'`
echo_success

echo -n "Add operation..."
benchmark_submit_float "Memory Add operation" `stream-mem | grep "^Add" | \
	awk '{print $2}'`
echo_success

echo -n "Triad operation..."
benchmark_submit_float "Memory Triad operation" `stream-mem | grep "^Triad" | \
	awk '{print $2}'`
echo_success

test_succeeded
