#!/bin/sh -e
# NAME=Unixbench
# DESCRIPTION=UNIX Bench Multi-CPU benchmark
# DESTROYS_HDD=false
# POWEROFF_DURING_TEST=false
# VERSION=0.1
# TAGS=benchmark,cpu,stress,memory,ram

. /usr/share/inquisitor/functions-test

exit_handler()
{
	[ -d "$WORKING_DIR" ] && rm -rf "$WORKING_DIR"
	cd $HOME
}

WORKING_DIR=`mktemp -d`

echo -n "Running UNIX Bench Multi-CPU benchmark..."
cd $WORKING_DIR
mkdir pgms testdir results tmp
cp $LIB_DIR/unixbench/* pgms/
mv pgms/dc.dat testdir/
mv pgms/sort.src testdir/

benchmark_submit_float "All CPUs score" `unixbench | tee $DEBUG_TTY | grep "Index Score" | sed -n "$ p" | awk '{print $NF}'`
echo_success
test_succeeded
