#!/bin/sh -e
# client/test/unixbench - A part of Inquisitor project
# Copyright (C) 2004-2008 by Iquisitor team 
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# NAME=Unixbench
# DESCRIPTION=UNIX Bench Multi-CPU benchmark
# DESTROYS_HDD=false
# POWEROFF_DURING_TEST=false
# VERSION=0.1
# TAGS=benchmark,cpu,stress,memory,ram
# DEPENDS=CPU,Memory,Mainboard

. /usr/share/inquisitor/functions-test

exit_handler()
{
	[ -d "$WORKING_DIR" ] && rm -rf "$WORKING_DIR"
	cd $HOME
}

WORKING_DIR=`mktemp -d`

echo -n "Running UNIX Bench Multi-CPU benchmark..."
cd $WORKING_DIR
mkdir pgms testdir results tmp
cp $LIB_DIR/unixbench/* pgms/
mv pgms/dc.dat testdir/
mv pgms/sort.src testdir/

benchmark_submit_float "All CPUs score" `unixbench | tee $DEBUG_TTY | \
	grep "Index Score" | sed -n "$ p" | awk '{print $NF}'`
echo_success
test_succeeded
