#!/bin/sh -ef
# NAME=Whetstone
# DESCRIPTION=Whetstone floating-point calculations benchmark
# DESTROYS_HDD=false
# POWEROFF_DURING_TEST=false
# VERSION=0.1
# TAGS=benchmark,cpu
# DEPENDS=CPU
# VAR=LOOPS:int:20000:Loop count

. /usr/share/inquisitor/functions-test

exit_handler()
{
	[ -f "$RESULT_FILE" ] && rm -f $RESULT_FILE
}

CPU_QUANTITY=`grep processor /proc/cpuinfo | wc -l`

for i in `seq 0 $(($CPU_QUANTITY - 1))`; do
	echo -n "Whetstone on core $i"
	result=`taskset -c $i whetstone $LOOPS 2>&1 | grep Whetstones | \
		awk '{print $6}'`
	echo_success
	benchmark_submit_float "Core $i MIPS" "$result"
done

test_succeeded
