#!/bin/sh

modprobe processor
modprobe ac
modprobe battery

rm -f ~/battery.log
pushd . >/dev/null
if cd /proc/acpi/ac_adapter/* 2>/dev/null; then
	AC_DIR=`pwd`
	cat * >>~/battery.log
fi
if cd /proc/acpi/battery/* 2>/dev/null; then
	BATTERY_DIR=`pwd`
	cat * >>~/battery.log
fi
popd >/dev/null

if [ -f ~/battery.log ]; then
	publish ~/battery.log

	BATTERY_VENDOR=`grep 'OEM info:' ~/battery.log | cut -c26- | ruby -e 'print $stdin.read.strip'`
	BATTERY_MODEL=`grep 'model number:' ~/battery.log | cut -c26- | ruby -e 'print $stdin.read.strip'`
	BATTERY_SERIAL=`grep 'serial number:' ~/battery.log | cut -c26- | ruby -e 'print $stdin.read.strip'`

	echo "Battery	$BATTERY_VENDOR	$BATTERY_MODEL	$BATTERY_SERIAL" >>~/DEVICES
	publish ~/DEVICES
fi
