#!/bin/sh
# NAME=BBU detect
# DESCRIPTION=Get BBU information through einarc.
# DEPENDS=BBU

einarc --list | while read adapter; do
	adapter_type=`echo "$adapter" | cut -f1`
	adapter_number=`echo "$adapter" | cut -f2`
	if INFO=`einarc --type=$adapter_type --adapter=$adapter_number bbu info`; then
		MANUFACTURER=`echo "$INFO" | cut -f1`
		MODEL=`echo "$INFO" | cut -f2`
		SERIAL=`echo "$INFO" | cut -f3`
		[ -n "$MODEL" ] && add_component 'BBU' "$MANUFACTURER" "$MODEL" "$SERIAL" ''
	fi
done
