#!/bin/sh

modprobe uhci-hcd

sleep 1

modprobe hci-usb
modprobe l2cap

sleep 1

# Check if any hci0 came available
if hciconfig hci0 2>/dev/null | grep -q hci0; then
	hciconfig hci0 up
	hciconfig -a >~/bluetooth.log
	BT_VENDOR=`cat ~/bluetooth.log | sed -ne '/Manufacturer: / s/^.*Manufacturer: \(.*\)$/\1/ p' | sed 's/Cambridge Silicon Radio/CSR/g;'`
	BT_PRODUCT=`cat ~/bluetooth.log | sed -ne '/HCI Rev: / s/^.*HCI Rev: \([^ ]*\) .*$/HCI Rev: \1/ p'`
	BT_TYPE=`cat ~/bluetooth.log | sed -ne '/Type: / s/^.*Type: \(.*\)$/\1/ p'`
	BT_ADDR=`cat ~/bluetooth.log | sed -ne '/BD Address: / s/^.*BD Address: \([0-9A-Z:]*\) .*$/\1/ p'`
	echo "Bluetooth	$BT_VENDOR	$BT_PRODUCT ($BT_TYPE)	$BT_ADDR" >>~/DEVICES

	publish ~/DEVICES
	publish ~/bluetooth.log
fi

# Check for WiFi-Bluetooth combined PCI cards
if lspci -n | grep -q 'Class 0200: 17fe:2220'; then
	BT_SLOT=`lspci -n | sed -ne '/Class 0200: 17fe:2220/ s/ .*$//p;' | tail -n1`
	BT_VENDOR=`lspci -vms $BT_SLOT | sed -ne '/^Vendor:/ s/^.*\t//p;'`
	BT_PRODUCT=`lspci -vms $BT_SLOT | sed -ne '/^Device:/ s/^.*\t//p;' | tail -n1`

	echo "Bluetooth	$BT_VENDOR	$BT_PRODUCT	" >>~/DEVICES
	echo "WiFi	$BT_VENDOR	$BT_PRODUCT	" >>~/DEVICES

	publish ~/DEVICES
fi
