#!/bin/sh

manufacturer=`ipmitool mc info | sed -n '/Manufacturer Name/s/^.*: \(.*\)$/\1/gp'`
device=`ipmitool mc info | sed -n '/Product ID/s/^.*: \(.*\)$/\1/gp'`
serial=`ipmitool lan print | grep "MAC Address" | awk '{print $NF}'`

$SHARE_DIR/add-component "Baseboard management controller" "$manufacturer" "$device" "$serial"
