#!/bin/sh

TYPES='IDE interface
RAID bus controller
Mass storage controller
SCSI storage controller'

echo "$TYPES" | while read TYPE; do
	CTRLS=`cat $HOME/lspci.log 2>/dev/null | grep -i "$TYPE" || true`
	echo "$CTRLS" | while read CTRL; do
		if [ -n "$CTRL" ]; then
			BUS=`echo "$CTRL" | grep -o  '..:..\..'`
			CTRL_INFO=`cat $HOME/lshw.log 2>/dev/null | grep -i -B3 "$BUS"$`
			CTRL_VENDOR=`echo "$CTRL_INFO" | sed -n 's/ *vendor: //p'`
			CTRL_MODEL=`echo "$CTRL_INFO" | sed -n 's/ *product: //p'`
			if [ -z "`echo "$CTRL_VENDOR" | grep -i 'lsi'`" ] && [ -z "`echo "$CTRL_VENDOR" | grep -i 'areca'`" ] && [ -z "`echo "$CTRL_VENDOR" | grep -i 'adaptec'`" ] || [ -n "`echo "$CTRL_MODEL" | grep -i 'SAS1064E'`" ] || [ -n "`echo "$CTRL_VENDOR" | grep -i 'mpt'`" ]; then
				$SHARE_DIR/add-component 'Disk Controller' "$CTRL_VENDOR" "$CTRL_MODEL" ''
			fi
		fi	
	done
done

einarc -l | while read L; do
	CTRL_TYPE=`echo "$L" | cut -f1`
	CTRL_MODEL=`echo "$L" | cut -f3`
	CTRL_SERIAL=`einarc -t $CTRL_TYPE adapter info | sed -n "s/Serial number\t//p" | sed 's/[^ -~]//g'`
	if [ "$CTRL_TYPE" = "areca" ]; then
		CTRL_VENDOR='Areca'
	elif [ "$CTRL_TYPE" = "lsi_megarc" ]; then
		CTRL_VENDOR='LSI'
	elif [ "$CTRL_TYPE" = "lsi_megcli" ]; then
		CTRL_VENDOR='LSI'
	elif [ "$CTRL_TYPE" = "adaptec_aaccli" ]; then
		CTRL_VENDOR='Adaptec'
	fi
	$SHARE_DIR/add-component 'Disk Controller' "$CTRL_VENDOR" "$CTRL_MODEL" "$CTRL_SERIAL"
done
