#!/bin/sh

LAST_PH_ID=''

cat /proc/cpuinfo | grep 'processor' | while read P; do
    CPU_INFO=`cat /proc/cpuinfo | grep -A8 "$P"`
    PH_ID=`echo "$CPU_INFO" | grep -m1 'physical id' || true`
    if [ "$PH_ID" != "$LAST_PH_ID" ] || [ -z "$PH_ID" ]; then
        CPU_VENDOR=`echo "$CPU_INFO" | sed -n 's/vendor_id.*: //p' | sed 's/Genuine//g;s/Authentic//g;'`
        CPU_MODEL=`echo "$CPU_INFO" | sed -n 's/model name.*: //p' | sed 's/(R)//g;s/(tm)//g;s/processor//ig;s/CPU//g;s/Intel//g;s/AMD//g;s/Genuine/Core Solo/;s/  */ /g;s/^ *//g;'`
	LAST_PH_ID="$PH_ID"
        $SHARE_DIR/add-component CPU "$CPU_VENDOR" "$CPU_MODEL" ''        
    fi
done
