#!/bin/sh
# client/detect/cpu - A part of Inquisitor project
# Copyright (C) 2004-2008 by Iquisitor team 
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

PROCESSORS=`ruby -e "text = File.read('/proc/cpuinfo')
infos = text.split('processor')
infos.shift

cores = infos.map do |inf|
	{ :vendor => inf.grep(/vendor_id/)[0].to_s.gsub(/^vendor_id.*: /, '').chomp,
	:model => inf.grep(/model name/)[0].to_s.gsub(/^model name.*: /, '').chomp,
	:core_id => inf.grep(/core id/)[0].to_s.gsub(/^core id.*: /, '').chomp.to_i }
end

processors = cores.select{ |c| c[:core_id] == 0 }.map do |c|
	\"CPU_VENDOR='#{c[:vendor]}'; CPU_MODEL='#{c[:model]}'\"
end

processors.each{ |p| puts p }"`

echo "$PROCESSORS" | while read I; do
	eval "$I"
	CPU_VENDOR=`echo "$CPU_VENDOR" | sed 's/^vendor: \([^;]*\);.*$/\1/' | sed 's/Genuine//g;s/Authentic//g;'`
	CPU_MODEL=`echo "$CPU_MODEL" | sed 's/^.*model: \([^;]*\);.*$/\1/' | sed 's/(R)//g;s/(tm)//g;s/processor//ig;s/CPU//g;s/Intel//g;s/AMD//g;s/Genuine/Core Solo/;s/@ //;s/  */ /g;s/^ *//g;'`
	$SHARE_DIR/add-component CPU "$CPU_VENDOR" "$CPU_MODEL" ''	
done
