#!/bin/sh
# NAME=Floppy detect
# DESCRIPTION=Detect floppy drive using hal-device
# DEPENDS=Floppy

if [ `hal-find-by-property --key=storage.drive_type --string floppy | wc -l` -eq 0 ]; then
	true
else
	for UDI in `hal-find-by-property --key=storage.drive_type --string floppy`; do
		if [ `hal-get-property --udi "$UDI" --key storage.bus` == "usb" ]; then
			vendor=`hal-get-property --udi "$UDI" --key storage.vendor`
			model=`hal-get-property --udi "$UDI" --key storage.model`
			serial=`hal-get-property --udi "$UDI" --key storage.serial`
		else
			vendor="PC Floppy Drive"
			model="1.44 Floppy Drive"
			serial=""
		fi

		$SHARE_DIR/add-component "Floppy" "$vendor" "$model" "$serial"
	done
fi
