#!/bin/sh
# NAME=Floppy detect
# DESCRIPTION=Detect floppy drives using hal-device.
# DEPENDS=Floppy

if [ `hal-find-by-property --key=storage.drive_type --string floppy | wc -l` -eq 0 ]; then
	true
else
	for UDI in `hal-find-by-property --key=storage.drive_type --string floppy`; do
		storage_bus=`hal-get-property --udi "$UDI" --key storage.bus`
		if [ "$storage_bus" == "usb" ]; then
			vendor=`hal-get-property --udi "$UDI" --key storage.vendor`
			model=`hal-get-property --udi "$UDI" --key storage.model`
			serial=`hal-get-property --udi "$UDI" --key storage.serial`
			version=""
		else
			vendor="PC Floppy Drive"
			model="1.44 Floppy Drive"
			serial=""
			version=""
		fi

		add_component "Floppy" "$vendor" "$model" "$serial" "$version"
	done
fi
