#!/bin/sh

einarc -t lsi_megarc physical list | while read L; do
	if [ -n "$L" ]; then
		HDD_VENDOR=`echo "$L" | cut -f2 | cut -f1 -d' '`
		HDD_MODEL=`echo "$L" | cut -f2 | cut -f2 -d' '`
		HDD_SERIAL=`echo "$L" | cut -f4`
		$SHARE_DIR/add-component HDD "$HDD_VENDOR" "$HDD_MODEL" "$HDD_SERIAL"
	fi
done
