#!/bin/sh

FW_SLOT=`lspci -n | sed -ne '/Class 0c00/ s/ .*$//p;'`

if [ -n "$FW_SLOT" ]; then

	FW_VENDOR=`lspci -vms $FW_SLOT | sed -ne '/^Vendor:/ s/^.*\t//p;'`
	FW_PRODUCT=`lspci -vms $FW_SLOT | sed -ne '/^Device:/ s/^.*\t//p;' | tail -n1`

	echo -n "Firewire	$FW_VENDOR	$FW_PRODUCT	" >>~/DEVICES
	pushd /sys/bus/ieee1394/devices/ >/dev/null
	sleep 2
	cd 0*
	if [ -r guid ]; then
		echo -n 'Firewire GUID	' >>~/SERIALS
		cat guid >>~/SERIALS
		cat guid >>~/DEVICES
	else
		echo 'Detected firewire, but unable to get GUID!'
		echo >>~/DEVICES
	fi
	publish ~/SERIALS
	publish ~/DEVICES
	popd >/dev/null
fi
