#!/bin/sh

ipmitool fru || true > $HOME/fru.log

FRU_INFO=`cat fru.log | grep -A13 'Builtin FRU Device'`
if [ -n "$FRU_INFO" ]; then
	CHASSIS_VENDOR=`echo "$FRU_INFO" | sed -n 's/ Product Manufacturer *: //p'`
	CHASSIS_TYPE=`echo "$FRU_INFO" | sed -n 's/ Chassis Type *: //p' | sed 's/Unspecified//'`
	CHASSIS_PART_NUM=`echo "$FRU_INFO" | sed -n 's/ Chassis Part Number *: //p' | sed 's/Unspecified//'`
	CHASSIS_SERIAL=`echo "$FRU_INFO"| sed -n 's/ Chassis Serial *: //p'`
	if [ -z "$CHASSIS_TYPE" ] || [ -z "$CHASSIS_PART_NUM" ]; then
		SEP=''
	else
		SEP='/'
	fi
	CHASSIS_MODEL="$CHASSIS_TYPE $SEP $CHASSIS_PART_NUM"
	$SHARE_DIR/add-component Chassis "$CHASSIS_VENDOR" "$CHASSIS_MODEL" "$CHASSIS_SERIAL"
	
	MB_VENDOR=`echo "$FRU_INFO" | sed -n 's/ Board Mfg *: //p'`
	MB_PRODUCT=`echo "$FRU_INFO" | sed -n 's/ Board Product *: //p'`
	MB_PART_NUM=`echo "$FRU_INFO" | sed -n 's/ Board Part Number *: //p'`
	MB_SERIAL=`echo "$FRU_INFO" | sed -n 's/ Board Serial *: //p'`
	if [ -z "$MB_PRODUCT" ] || [ -z "$MB_PART_NUM" ]; then
		SEP=''
	else
		SEP='/'
	fi
	MB_MODEL="$MB_PRODUCT $SEP $MB_PART_NUM"
	$SHARE_DIR/add-component Mainboard "$MB_VENDOR" "$MB_MODEL" "$MB_SERIAL"
	
	PLATFORM_VENDOR=`echo "$FRU_INFO" | sed -n 's/ Product Manufacturer *: //p'`
	PLATFORM_PRODUCT=`echo "$FRU_INFO" | sed -n 's/ Product Name *: //p'`
	PLATFORM_PART_NUM=`echo "$FRU_INFO" | sed -n 's/ Product Part Number *: //p'`
	PLATFORM_SERIAL=`echo "$FRU_INFO" | sed -n 's/ Product Serial *: //p'`
	if [ -z "$PLATFORM_PRODUCT" ] || [ -z "$PLATFORM_PART_NUM" ]; then
		SEP=''
	else
		SEP='/'
	fi
	PLATFORM_MODEL="$PLATFORM_PRODUCT $SEP $PLATFORM_PART_NUM"
	$SHARE_DIR/add-component Platform "$PLATFORM_VENDOR" "$PLATFORM_MODEL" "$PLATFORM_SERIAL"
fi

PS_INFO=`cat fru.log | grep -A9 'ps.vpd'`
if [ -n "$PS_INFO" ]; then
	PS_VENDOR=`echo "$PS_INFO" | sed -n 's/ Product Manufacturer *: //p'`
	PS_MODEL=`echo "$PS_INFO" | sed -n 's/ Product Part Number *: //p'`
	PS_SERIAL=`echo "$PS_INFO" | sed -n 's/ Product Serial *: //p'`
	$SHARE_DIR/add-component 'Power Supply' "$PS_VENDOR" "$PS_MODEL" "$PS_SERIAL"
fi

BP_INFO=`cat fru.log | grep -A9 'scsibp.vpd'`
if [ -n "$BP_INFO" ]; then
	BP_VENDOR=`echo "$BP_INFO" | sed -n 's/ Product Manufacturer *: //p'`
	BP_MODEL=`echo "$BP_INFO" | sed -n 's/ Product Part Number *: //p'`
	BP_SERIAL=`echo "$BP_INFO" | sed -n 's/ Product Serial *: //p'`
	$SHARE_DIR/add-component 'SCSI Backplane' "$BP_VENDOR" "$BP_MODEL" "$BP_SERIAL"
fi

rm -f $HOME/fru.log
