#!/bin/sh

MODEM_SLOT=`lspci | grep 'Communication controller' | sed 's/ .*$//g;'`

if [ -z "$MODEM_SLOT" ]; then
	MODEM_SLOT=`lspci | grep 'Modem' | sed 's/ .*$//g;'`
fi

if [ -n "$MODEM_SLOT" ]; then
	lspci -vs $MODEM_SLOT >~/modem.log
	lspci -nvs $MODEM_SLOT >>~/modem.log
	MODEM_VENDOR=`lspci -vms $MODEM_SLOT | sed -ne '/^Vendor:/ s/^.*\t//p;'`
	MODEM_DEVICE=`lspci -vms $MODEM_SLOT | sed -ne '/^Device:/ s/^.*\t//p;' | tail -n1`

	echo "Modem	$MODEM_VENDOR	$MODEM_DEVICE	" >>~/DEVICES
	publish ~/DEVICES

fi

publish ~/modem.log
