#!/bin/sh

ifconfig eth0 >~/network.log
publish ~/network.log

MAC=`cat ~/network.log | grep HWaddr | sed 's/^.*HWaddr //g;'`
echo "Ethernet MAC	$MAC" >>~/SERIALS
publish ~/SERIALS

NETWORK_SLOT=`lspci -n | grep -v '17fe:2220' | sed -ne '/Class 0200/ s/ .*$//p;' | tail -n1`

if [ -n $NETWORK_SLOT ]; then
	lspci -vs $NETWORK_SLOT >>~/network.log
	lspci -vns $NETWORK_SLOT >>~/network.log
	publish ~/network.log

	NETWORK_VENDOR=`lspci -vms $NETWORK_SLOT | sed -ne '/^Vendor:/ s/^.*\t//p;'`
	NETWORK_DEVICE=`lspci -vms $NETWORK_SLOT | sed -ne '/^Device:/ s/^.*\t//p;' | tail -n1`

	echo "Ethernet	$NETWORK_VENDOR	$NETWORK_DEVICE	$MAC" >>~/DEVICES
	publish ~/DEVICES
else
	echo "WARNING: Unable to detect PCI network card"
fi
