#!/bin/sh

hal-find-by-property --key storage.drive_type --string cdrom | while read L; do
	OSD_MODEL=`hal-get-property --udi $L --key storage.model`
	if [ -n "$OSD_MODEL" ]; then
		$SHARE_DIR/add-component OSD "" "$OSD_MODEL" ""
	fi
done 
