#!/bin/sh
# client/detect/tape - A part of Inquisitor project
# Copyright (C) 2004-2008 by Iquisitor team 
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

for UDI in `hal-find-by-property --key scsi.type --string tape`; do
	vendor=`hal-get-property --udi "$UDI" --key scsi.vendor`
	model=`hal-get-property --udi "$UDI" --key scsi.model`
	$SHARE_DIR/add-component "Tape drive" "$vendor" "$model"
done
