#!/bin/sh -e
# client/detect/usb - A part of Inquisitor project
# Copyright (C) 2004-2008 by Iquisitor team 
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

for I in /sys/bus/usb/devices/*; do
	if [ -r "$I/manufacturer" ]; then
		MANUFACTURER=`cat "$I/manufacturer"`
	elif [ -r "$I/idVendor" ]; then
		MANUFACTURER=`cat "$I/idVendor"`
	else
		continue
	fi

	if [ -r "$I/product" ]; then
		PRODUCT=`cat $I/product`
	elif [ -r "$I/idProduct" ]; then
		PRODUCT=`cat $I/idProduct`
	else
		continue
	fi

	if [ -r "$I/serial" ]; then
		SERIAL=`cat $I/serial`
	else
		SERIAL=
	fi

	# Strip out unnecessary devices
	if echo "$MANUFACTURER" | grep -q "^`uname -sr`"; then
		continue
	fi

	$SHARE_DIR/add-component USB "$MANUFACTURER" "$PRODUCT" "$SERIAL"
done
