#!/bin/sh

VIDEO_SLOT=`lspci -n | sed -ne '/Class 0300/ s/ .*$//p;' | tail -n1`

if [ -n $VIDEO_SLOT ]; then
	lspci -vs $VIDEO_SLOT >>~/video.log
	lspci -vns $VIDEO_SLOT >>~/video.log
	publish ~/video.log

	VIDEO_VENDOR=`lspci -vms $VIDEO_SLOT | sed -ne '/^Vendor:/ s/^.*\t//p;'`
	VIDEO_DEVICE=`lspci -vms $VIDEO_SLOT | sed -ne '/^Device:/ s/^.*\t//p;' | tail -n1`
	VIDEO_SVENDOR=`lspci -nvms $VIDEO_SLOT | sed -ne '/^SVendor:/ s/^.*\t//p;'`
	VIDEO_SDEVICE=`lspci -nvms $VIDEO_SLOT | sed -ne '/^SDevice:/ s/^.*\t//p;'`

	echo "Video	$VIDEO_VENDOR	$VIDEO_DEVICE ($VIDEO_SVENDOR:$VIDEO_SDEVICE)	" >>~/DEVICES
	publish ~/DEVICES
else
	echo "WARNING: Unable to detect videocard on PCI"
fi
