#!/bin/sh

if lspci -n | grep -q 'Class 0d10'; then
	WIFI_SLOT=`lspci -n | grep 'Class 0d10' | sed 's/ .*$//g;'`
fi

# Workaround for ugly RTL 8180 WiFi card
if lspci -n | grep -q 'Class 0200: 10ec:8180'; then
	WIFI_SLOT=`lspci -n | grep 'Class 0200: 10ec:8180' | sed 's/ .*$//g;'`
fi

# Very buggy RTL 8180 card with broken VendorID
if lspci -n | grep -q 'Class 0200: 01ec:8180'; then
	WIFI_SLOT=`lspci -n | grep 'Class 0200: 01ec:8180' | sed 's/ .*$//g;'`
fi

# Workaround for ugly Intel cards, what use class 0280
if lspci -n | grep -q 'Class 0280'; then
	WIFI_SLOT=`lspci -n | grep 'Class 0280' | sed 's/ .*$//g;'`
fi

if [ -n "$WIFI_SLOT" ]; then
	lspci -s $WIFI_SLOT >>~/wifi.log
	lspci -n -s $WIFI_SLOT >>~/wifi.log
	WIFI_VENDOR=`lspci -vms $WIFI_SLOT | sed -ne '/^Vendor:/ s/^.*\t//p;'`
	WIFI_PRODUCT=`lspci -vms $WIFI_SLOT | sed -ne '/^Device:/ s/^.*\t//p;' | tail -n1 | sed 's/(R)//g;s/Intel//g;s/^  *//g;'`
	echo "WiFi	$WIFI_VENDOR	$WIFI_PRODUCT	" >>~/DEVICES
fi

# Check for USB WiFi adapter
if [ -d /sys/bus/usb/drivers/usb/3-1/ ]; then
	WIFI_VENDOR=`cat /sys/bus/usb/drivers/usb/3-1/manufacturer`
	WIFI_PRODUCT=`cat /sys/bus/usb/drivers/usb/3-1/product`
	echo "$WIFI_PRODUCT" >>~/wifi.log
	echo "WiFi	$WIFI_VENDOR	$WIFI_PRODUCT	" >>~/DEVICES
fi

[ -r ~/DEVICES ] && publish ~/DEVICES
[ -r ~/wifi.log ] && publish ~/wifi.log
