# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define() do

  create_table "component_groups", :force => true do |t|
    t.column "name",     :string,  :limit => 50
    t.column "info",     :string,  :limit => 60
    t.column "isactive", :integer, :limit => 6,  :default => 1, :null => false
  end

  create_table "component_models", :force => true do |t|
    t.column "vendor",             :string,  :limit => 128, :default => "", :null => false
    t.column "name",               :string,  :limit => 128
    t.column "component_group_id", :integer
    t.column "hw_info",            :string,  :limit => 70
    t.column "isactive",           :integer, :limit => 6,   :default => 1,  :null => false
  end

  add_index "component_models", ["vendor"], :name => "vendor"

  create_table "components", :id => false, :force => true do |t|
    t.column "srvhw_id",           :integer,                                      :null => false
    t.column "testing_id",         :integer
    t.column "component_model_id", :integer
    t.column "hw_qty",             :integer, :limit => 6
    t.column "hw_serial",          :string,  :limit => 30, :default => "sticker"
  end

  create_table "computers", :force => true do |t|
    t.column "serial_no",    :integer,                              :null => false
    t.column "model_id",     :integer
    t.column "customer_id",  :integer
    t.column "tester_id",    :integer, :limit => 20, :default => 1
    t.column "assembler_id", :integer, :limit => 20, :default => 1
    t.column "shelf",        :string,  :limit => 8
    t.column "doc_no",       :string,  :limit => 10
  end

  create_table "customers", :force => true do |t|
    t.column "name",     :string,  :limit => 60
    t.column "info",     :string,  :limit => 100
    t.column "isactive", :integer, :limit => 6,   :default => 1, :null => false
  end

  create_table "hardware_params", :id => false, :force => true do |t|
    t.column "param_name",  :string,  :limit => 25
    t.column "param_id",    :integer,                :null => false
    t.column "description", :string,  :limit => 250
  end

  create_table "log_data", :id => false, :force => true do |t|
    t.column "log_id",    :integer
    t.column "log_time",  :datetime
    t.column "log_text",  :string,   :limit => 250
    t.column "log_cat",   :string,   :limit => 250
    t.column "log_level", :integer,                 :default => 0
  end

  create_table "macs", :id => false, :force => true do |t|
    t.column "current_id", :integer
    t.column "mac",        :string,  :limit => 250
  end

  create_table "mb_bios", :id => false, :force => true do |t|
    t.column "hw_id", :integer
    t.column "bios",  :string,  :limit => 250
    t.column "use",   :string,  :limit => 250
  end

  create_table "models", :force => true do |t|
    t.column "name",     :string,  :limit => 250
    t.column "stages",   :string,  :limit => 250, :default => "mb_bios raid_bios test memtest stress server dmi"
    t.column "dmi_name", :string,  :limit => 250, :default => "",                                                 :null => false
    t.column "ismodel",  :integer, :limit => 6,   :default => 1
    t.column "mask",     :integer, :limit => 6,   :default => 0,                                                  :null => false
  end

  create_table "order_lines", :force => true do |t|
    t.column "order_id", :integer,                                :null => false
    t.column "name",     :string,  :limit => 250, :default => "", :null => false
    t.column "qty",      :integer,                                :null => false
  end

  add_index "order_lines", ["order_id"], :name => "order_id"

  create_table "orders", :force => true do |t|
    t.column "doc_no",     :string,  :limit => 64
    t.column "manager_id", :integer
  end

  create_table "people", :force => true do |t|
    t.column "login",        :string,  :limit => 32
    t.column "name",         :string,  :limit => 128
    t.column "is_tester",    :boolean,                :default => false, :null => false
    t.column "is_assembler", :boolean,                                   :null => false
  end

  create_table "raid_bios", :id => false, :force => true do |t|
    t.column "hw_id", :integer
    t.column "bios",  :string,  :limit => 250
    t.column "use",   :string,  :limit => 250
  end

  create_table "servers_params", :id => false, :force => true do |t|
    t.column "param_value", :integer, :limit => 20
    t.column "unisrv_id",   :integer
    t.column "param_id",    :integer
  end

  create_table "stages", :id => false, :force => true do |t|
    t.column "stage_id",   :integer,                :null => false
    t.column "stage_name", :string,  :limit => 250
    t.column "stage_desc", :string,  :limit => 250
    t.column "model_id",   :integer
    t.column "stage_text", :string,  :limit => 40
  end

  create_table "template_hardware", :id => false, :force => true do |t|
    t.column "hw_id",       :integer
    t.column "template_id", :integer
    t.column "qty",         :integer, :limit => 20
  end

  create_table "template_hardware_params", :id => false, :force => true do |t|
    t.column "template_id", :integer
    t.column "param_id",    :integer
    t.column "value",       :integer, :limit => 20
  end

  create_table "templates", :id => false, :force => true do |t|
    t.column "template_id",   :integer,               :null => false
    t.column "template_name", :string,  :limit => 40
    t.column "template_desc", :string,  :limit => 60
    t.column "model_id",      :integer
  end

  create_table "testing_stages", :id => false, :force => true do |t|
    t.column "testing_id", :integer,                                :null => false
    t.column "stage",      :string,   :limit => 64
    t.column "start",      :datetime
    t.column "end",        :datetime
    t.column "result",     :integer,                :default => 0,  :null => false
    t.column "comment",    :text,                   :default => "", :null => false
  end

  add_index "testing_stages", ["testing_id"], :name => "testing_id"
  add_index "testing_stages", ["testing_id", "start"], :name => "testing_id_2"

  create_table "testings", :force => true do |t|
    t.column "computer_id", :integer
    t.column "test_start",  :datetime
    t.column "test_end",    :datetime
    t.column "profile_id",  :integer
  end

  add_index "testings", ["computer_id"], :name => "computer_id"

end
