#!/bin/sh

# Redmine 135 issue workaround
rm135_hack()
{
	# Look for proper ttyUSB device
	for mdm in /dev/ttyUSB*; do
		echo Trying to guess NL300 on $mdm
		chat -t 5 -Vs ABORT ERROR '' SN A0 SI POST <$mdm>$mdm 2>$TMP_DIR/nl300
		COMPUTER_ID="$(sed -n 's/^[0]*\([0-9]\+\)$/\1/p' < $TMP_DIR/nl300)"
		rm -f $TMP_DIR/nl300
		[ -z "$COMPUTER_ID" ] || break
	done
	[ -n "$COMPUTER_ID" ] || export COMPUTER_ID_TO_BE_FLASHED=1
}

COMPUTER_ID=`xmlstarlet sel -t -v "list/component[vendor='Tennex Systems Ltd.']/serial" <$HOME/components.xml | sed 's/^00*//';`
[ -z "$COMPUTER_ID" ] && 
	COMPUTER_ID=`xmlstarlet sel -t -v "list/component[vendor='Tennex Systems']/serial" <$HOME/components.xml | sed 's/^00*//';`
# WRND: temporary due to #RM:135
if [ -z "$COMPUTER_ID" ]; then
	COMPUTER_ID=`xmlstarlet sel -t -v "list/component[vendor='Tennex']/serial" <$HOME/components.xml | sed 's/^00*//';`
	[ -z "$COMPUTER_ID" ] || rm135_hack
fi
