#===============================================================================
# A build configuration file for Inquisitor
#
# Edit to suit your preferences for the build
#===============================================================================

# Inquisitor platform version
# Displayed everywhere applicable
INQ_VERSION=3.0

#===============================================================================
# Client settings
#===============================================================================

# Flavour of Inquisitor to build
# Valid values: live, enterprise
FLAVOUR=live

# Target architecture to build client for
# Valid values: i586, x86_64
TARGET=x86_64

# Directories to install files into
BIN_DIR=/usr/bin
ETC_DIR=/etc/inquisitor
ifeq ($(TARGET), x86_64)
LIB_DIR=/usr/lib64/inquisitor
else
LIB_DIR=/usr/lib/inquisitor
endif
SHARE_DIR=/usr/share/inquisitor

# Einarc modules to build in comma-separated list or 'all' to build everything
EINARC_MODULES=all

# tty device to flush all mass progress/debug into
DEBUG_TTY=/dev/tty2

#===============================================================================
# Client image settings
#===============================================================================

# Client image would be built from this system.
# Valid values: altlinux, debian, suse
CLIENT_BASE=altlinux

# Local build paths
REPO_HUGE=$(PWD)/repo-huge
IMAGE_DIR=image

#===============================================================================
# Server settings
# These are used only in full client-server build

# Server host to deploy client image to
DEPLOY_HOST=inq

# Path on DEPLOY_HOST to client image that will be exported using NFS
DEPLOY_PATH=/inq/root-$(TARGET)
