#!/bin/sh -e
# ID=3
# NAME=CPU core voltage (ipmi)
# DESCRIPTION=This monitoring uses ipmitool for getting CPU's core voltage.
# MEASUREMENT=voltage

. _inq-config-global; . $SHARE_DIR/functions-monitoring
[ -n "$PERIOD" ] || PERIOD=60

while true; do
	ipmitool sdr type Voltage 2>$DEBUG_TTY |
		grep -i core |
		awk -F'|' '{print $NF}' |
		sed -n 's/^ //g; s/^\([0-9\.]*\) .*$/\1/gp' |
		cat -n |
	while read entity; do
		[ -z "$entity" ] || monitoring_submit $entity 0 # Zero is precaution for an empty value
	done

	sleep $PERIOD
done
