#!/bin/sh -e
# ID=1
# NAME=CPU temperature (ipmi)
# DESCRIPTION=This monitoring uses ipmitool for getting CPU's temperature.
# MEASUREMENT=temperature

. _inq-config-global; . $SHARE_DIR/functions-monitoring
[ -n "$PERIOD" ] || PERIOD=30

# Bail out early if we have no IPMI
has_ipmi || exit 1

while true; do
	ipmitool sdr type Temperature |
		grep -i cpu |
		awk -F'|' '{print $NF}' |
		sed -n 's/^ //g; s/^\([0-9\.]*\) .*$/\1/gp' |
		cat -n |
	while read entity; do
		[ -z "$entity" ] || monitoring_submit $entity 0 # Zero is precaution for an empty value
	done

	sleep $PERIOD
done
