#!/bin/sh -e
# ID=4
# NAME=CPU core voltage (sensors)
# DESCRIPTION=This monitoring uses sensors for getting CPU's vcore.
# MEASUREMENT=voltage

. _inq-config-global; . $SHARE_DIR/functions-monitoring
[ -n "$PERIOD" ] || PERIOD=60

while true; do
	sensors -A 2>$DEBUG_TTY | while read sensor; do
		voltage=`echo "$sensor" | sed -n "s/^VCore \([0-9]*\):.*+\([0-9\.]*\) V .*$/\1 \2/p"`
		[ -z "$voltage" ] || monitoring_submit $voltage 0 # Zero is precaution for an empty value
	done

	sleep $PERIOD
done
