#!/bin/sh -e
# ID=8
# NAME=OS load average
# DESCRIPTION=GNU/Linux operating system's load average. Load average figures giving the number of jobs in the run queue or waiting for disk I/O.
# MEASUREMENT=load

. `dirname $0`/../functions-monitoring
[ -n "$PERIOD" ] || PERIOD=60

while true; do
	monitoring_submit 0 `cat /proc/loadavg | awk '{print $1}'`
	sleep $PERIOD
done
