#!/bin/sh -e
# ID=6
# TITLE=ODD-READ
# MEASUREMENT=speed
# This is not a real monitoring: it runs only once during odd_read
# test, that submits drive speed. You can view actual code in
# client/test/odd_read in generate_speed_results function.
