#!/usr/bin/env ruby
# client/main/add-component - A part of Inquisitor project
# Copyright (C) 2004-2008 by Iquisitor team 
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

COMP_FILE = "#{ENV['HOME']}/components.xml"

require 'rexml/document'

type = REXML::Element.new 'type'
type.text = ARGV[0]

vendor = REXML::Element.new 'vendor'
vendor.text = ARGV[1]

model = REXML::Element.new 'model'
model.text = ARGV[2]

serial = REXML::Element.new 'serial'
serial.text = ARGV[3]

comp = REXML::Element.new 'component'
comp.add_element type
comp.add_element vendor
comp.add_element model
comp.add_element serial

begin
	doc = REXML::Document.new(File.new(COMP_FILE))
rescue Errno::ENOENT
	doc = REXML::Document.new
	doc.add_element(REXML::Element.new('list'))
end

doc.root.add_element comp

File.open(COMP_FILE, 'w') { |f|
	doc.write f
}
