#!/usr/bin/env ruby

COMP_FILE = "#{ENV['HOME']}/components.xml"

require 'rexml/document'

type = REXML::Element.new 'type'
type.text = ARGV[0]

vendor = REXML::Element.new 'vendor'
vendor.text = ARGV[1]

model = REXML::Element.new 'model'
model.text = ARGV[2]

serial = REXML::Element.new 'serial'
serial.text = ARGV[3]

version = REXML::Element.new 'version'
version.text = ARGV[4]

comp = REXML::Element.new 'component'
comp.add_element type
comp.add_element vendor
comp.add_element model
comp.add_element serial
comp.add_element version

begin
	doc = REXML::Document.new(File.new(COMP_FILE))
rescue Errno::ENOENT
	doc = REXML::Document.new
	doc.add_element(REXML::Element.new('list'))
end

doc.root.add_element comp

File.open(COMP_FILE, 'w') { |f|
	doc.write(f, indent = 0)
}
