#!/bin/sh

#prepare_pxelinux()
#{
#	BOOT_IMAGE=$1
#
#	other_macs=`ifconfig | grep "^eth[0-9]* " | sed 's/^.*HWaddr //g;s/:/-/g;y/ABCDEF/abcdef/;s/^/01-/' | perl -e '@l=map{split}<>;print join ",",@l'`
#
#	for mac in `ifconfig | grep "^eth[0-9]* " | sed 's/^.*HWaddr //g;s/:/-/g;y/ABCDEF/abcdef/;s/^/01-/'`; do
#		ssh /usr/local/bin/prepare_pxelinux $mac $BOOT_IMAGE $other_macs
#	done
#}

echo "Detecting if we need to reflash BIOS"

if grep -q "E-9722R" /home/fru.log; then
	print_green_message "RS160G3 detected"
	version=`grep -A 8 "^BIOS Information" /home/dmi.log | grep Version | sed 's/.*Version: \(.*\)$/\1/'`
	print_green_message "BIOS Version: $version"
	if [ $version != "BIOS Version 1.94" ]; then
		print_red_message "An old BIOS version detected"
		print_red_message "Need to reflash BIOS"
		print_red_message "Reboot and press f for reflashing"
		read tmp
		#prepare_pxelinux rs160g3.bios
		#reboot
	fi
fi
