#!/bin/sh
# Obligatory functions to process before every test.

if [ -z "$PLANNER" ]; then
	# Running in free state; need to get all variable for test
	. /etc/inquisitor/global
	. $SHARE_DIR/functions
	. $SHARE_DIR/communication
	TEST_NAME=$0

	CPU_TEST_TIME=600
	CPU_LOG_TIME=30

	MEM_TEST_LOOPS=3
	MEM_LOG_TIME=30

	FDD_SIZE=1440

	FLASH_SIZE_LIMIT_MB=2048

	LOAD_ROOT="/tmp/stresstest"
	LOAD_TREE="/usr/share/inquisitor/linux-2.6.15-stress"
	LOAD_TEST_TIME=3600
	LOAD_LOG_TIME=60
else
	# Planner has supplied us all variables
	true
fi
