#!/usr/bin/env ruby
# client/main/hal-searcher - A part of Inquisitor project
# Copyright (C) 2004-2008 by Iquisitor team 
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

require 'getoptlong'

opts = GetoptLong.new(
	['--help', '-h', GetoptLong::NO_ARGUMENT],
	['--key', '-k', GetoptLong::REQUIRED_ARGUMENT],
	['--value', '-v', GetoptLong::REQUIRED_ARGUMENT]
)

key = nil
value = nil
opts.each do |opt, arg|
	case opt
	when '--help'
		puts 'usage: hal-finder --key <key> --value <value> [--help]'
		exit
	when '--key'
		key = arg
	when '--value'
		value = arg
	end	
end

hal_dump = `hal-device`.split("\n")
devices = []
h = {}
hal_dump.each do |l|
	h['udi'] = $1 if l =~ /^[0-9]+: udi = '(.+)'$/
	h[$1] = $2 if l =~ /^ *(.+) = '(.+)'  \(string\)$/
	h[$1] = $2.split(', ').map{ |s| s.gsub(/^'/, '').gsub(/'$/, '') } if l =~ /^ *(.+) = \{ ('.*', ('.*', )'.*'|'.*') \} \(string list\)$/
	h[$1] = $2 if l =~ /^ *(.+) = (.+)  \(.+\)  \(int\)$/
	if l == ''
		devices << h
		h = {}
	end
end
devices << h

finded = devices.select do |d|
	if d[key].class == Array
		d[key].find{ |x| x == value }
	else
		d[key] == value
	end
end

finded.each{ |d| puts d['udi'] }
