#!/bin/sh -ef

mount -n -t proc proc /proc
mount -n -t sysfs sysfs /sys

# Remount read-write
REMOUNTTAB=/etc/remounttab
if [ -s $REMOUNTTAB ]; then
	grep -ve '^\(#\|\$\)' $REMOUNTTAB | while read mntpt rest; do
		if [ -d $mntpt ]; then
			[ -z "$rest" ] || rest="-o $rest"
			echo -n "Remounting $mntpt read/write:"
			(cd $mntpt && tar cp --same-owner --same-permissions . 2>/dev/null) |\
			(mount -n -ttmpfs $rest /dev/shm $mntpt && tar xp -C $mntpt/ 2>/dev/null) && echo_success || echo_failure
		fi
	done
fi

LIVETAB=/etc/overlaytab
if [ -s $LIVETAB ]; then
	grep -ve '^\(#\|\$\)' $LIVETAB |while read mntpt; do
		if [ -d $mntpt ]; then
			mkdir -p /mnt/root/$mntpt
			echo -n "Remounting $mntpt to overlay:"
			mount -n -t unionfs -o dirs=/mnt/root/$mntpt=rw:$mntpt=ro null $mntpt && echo_success || echo_failure
		fi
	done
fi

#modprobe -a ide-core atiixp ide-generic ide-disk ide-cd
#modprobe thermal

/sbin/service udevd start
/sbin/service messagebus start
/sbin/service haldaemon start
/sbin/service sshd start
/sbin/service portmap start

/sbin/modprobe ipmi_si || :
/sbin/modprobe ipmi_devintf || :

# Mount NFS share containing firmwares, but do not fail
echo -n "Trying to mount firmwares share:"
mount -t nfs $SERVER:/inq/firmwares $SHARE_DIR/firmwares && echo_success || echo_failure

echo -n 'Starting lm_sensors detection'
$SHARE_DIR/inq-sensors-detect >/dev/null 2>/dev/null && echo_success || echo_failure

#rm -f /etc/passwd || fatal_failure 'Preparing initialization'
#rm -f /etc/group || fatal_failure 'Preparing initialization'

#touch -t 197001010000.00 /etc/modules.conf

#echo 'root:x:0:0::/home:/bin/bash' >/etc/passwd || fatal_failure 'Preparing /etc/passwd (root)'
#echo 'ntpd:x:113:57::/dev/null:/dev/null' >>/etc/passwd || fatal_failure 'Preparing /etc/passwd (ntpd)'
#echo 'root:x:0:root' >/etc/group || fatal_failure 'Preparing /etc/group'
#echo -n >/etc/fstab || fatal_failure 'Make null /etc/fstab'

# Set up MegaRAID device
if grep -q megadev /proc/devices; then
        MAJOR=`grep megadev /proc/devices | cut -f1 -d\ `
        mknod /dev/megadev0 c $MAJOR 0 || :
fi

# Set up Adaptec device
if grep -q aac /proc/devices; then
        MAJOR=`grep aac /proc/devices | cut -f1 -d\ `
        mknod /dev/aac0 c $MAJOR 0 || :
fi

echo -n 'Creating Inquisitor logging pipe'
mkfifo /dev/inqlog && echo_success || echo_failure

setterm -powersave off
