#!/bin/sh

. _inq-config-global
. $SHARE_DIR/functions
. $SHARE_DIR/communication

[ -n "$COMPUTER_ID" ] || COMPUTER_ID=`inq-self-id`
if ! [ -n "$COMPUTER_ID" ]; then
	echo_failure 'Self-identification failed'
	exit 1
else
	export COMPUTER_ID
fi

for I in $SHARE_DIR/monitoring/*; do
	monitoring=`basename $I`
	echo -n "Starting $monitoring"
	monitoring_start $monitoring
	echo_success
done
