#!/usr/bin/ruby -rubygems

require 'builder'
require 'open-uri'
require 'rexml/document'

computer_id = ENV['COMPUTER_ID']

puts(REXML::Document.new(open("http://#{ ENV['SERVER'] }/computers/plan/#{ ENV['COMPUTER_ID'] }.xml").read()).root.elements['script'].text())

