#!/bin/sh

. /etc/inquisitor/global

DIALOG=dialog

while true; do
	exec 3>&1
	value=`$DIALOG --item-help --nocancel --backtitle 'Inquisitor Live' \
	        --title 'Choose an action' --menu '' \
	        12 60 6 \
	        'Non-destructive' 'Non-destructive tests loop' '' \
		'Full' 'Full tests loop - WARNING! This test would overwrite all the data on your hard drive!' '' \
		'Detects' 'Detects only' '' \
		'View' 'View test results' '' \
		'Save' 'Save test results' 'Save test results to external storage media (USB flash, etc)' \
		'Reboot' 'Quit and reboot' '' \
	2>&1 1>&3`
	retval=$?
	exec 3>&-

	clear

	case $retval in
	0)
		;;
	1)
		exit 0
		;;
	255)
		if test -n "$value" ; then
			echo "$value"
		else
			continue # ESC pressed
		fi
		;;
	esac

	case "$value" in
	Non-destructive)
		cat <<__EOF__ >$HOME/test_script
PLANNER=1 TEST_NAME=cpu TESTTIME=1800 run_test cpu
PLANNER=1 TEST_NAME=memory TEST_LOOPS=1 LOGTIME=120 run_test memory
PLANNER=1 TEST_NAME=net URL=3000/test_file.html TIMEOUT=30 MD5=ca658fd4159bc35698edf9a1cdd70876 run_test net
PLANNER=1 TEST_NAME=fdd FLOPPY_SIZE=1440 run_test fdd
PLANNER=1 TEST_NAME=odd_read MESH_POINTS=1024 TEST_IMAGE_BLOCKS=50000 FORCE_NON_INTERACTIVE=false TEST_IMAGE_HASH=2e8744dfd11bf425001aad57976d42cc run_test odd_read
__EOF__
		inquisitor
		;;
	Full)
		if $DIALOG --backtitle 'Inquisitor Live: Full tests loop' --title 'WARNING!' --clear --yesno 'This is a full test that will overwrite all the contents of your hard drives! Are you sure you want to run this test?' 8 60; then
			clear
			cat <<__EOF__ >$HOME/test_script
PLANNER=1 TEST_NAME=cpu TESTTIME=1800 run_test cpu
PLANNER=1 TEST_NAME=memory TEST_LOOPS=1 LOGTIME=120 run_test memory
PLANNER=1 TEST_NAME=hdd-passthrough DISK_GROUP_SIZE=8 run_test hdd-passthrough
PLANNER=1 TEST_NAME=hdd-array JOBS=16 TIMEOUT=3600 STRESS_TREE=/usr/share/inquisitor/linux-2.6.22.5-31-stress.tar.gz LOGTIME=120 run_test hdd-array
PLANNER=1 TEST_NAME=net URL=3000/test_file.html TIMEOUT=30 MD5=ca658fd4159bc35698edf9a1cdd70876 run_test net
PLANNER=1 TEST_NAME=fdd FLOPPY_SIZE=1440 run_test fdd
PLANNER=1 TEST_NAME=odd_read MESH_POINTS=1024 TEST_IMAGE_BLOCKS=50000 FORCE_NON_INTERACTIVE=false TEST_IMAGE_HASH=2e8744dfd11bf425001aad57976d42cc run_test odd_read
__EOF__
			inquisitor
		else
			continue
		fi
		;;
	Detects)
		inq-detect
		;;
	View)
		;;
	Save)
		;;
	Reboot)
		/sbin/reboot
		;;
	esac

	echo
	echo 'Press ENTER to return to main menu'
	read L
done
