#!/bin/sh

spinner()
{
        chars=("-" "\\" "|" "/")
        count=0
        while true; do
                pos=$(( $count %4 ))
                echo -en "\b${chars[$pos]}"
                count=$(( count + 1 ))
                sleep 0.5
        done
}

spinner &

while true; do
        date
        sleep 1
done
