#!/bin/sh

export PATH=/sbin:/usr/sbin:/usr/local/sbin:/bin:/usr/bin:/usr/local/bin:/usr/X11R6/bin
export HOME=/home

. _inq-config-global
. $SHARE_DIR/functions

# Here we can safely start init, as this wrapper will be used only in
# LiveCD version
. $SHARE_DIR/init

SCREEN_SCENARIO=`mktemp`

cat > $SCREEN_SCENARIO <<__EOF__
split
resize -9
screen -t Watchdog $SHARE_DIR/inq-live-spinner
focus
screen -t Inquisitor inq-live

__EOF__

chmod 775 /var/run/screen
exec screen -c $SCREEN_SCENARIO
