#!/bin/sh
# client/main/inq-standalone - A part of Inquisitor project
# Copyright (C) 2004-2008 by Iquisitor team 
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

export LC_ALL=C

. /etc/inquisitor/global
. $SHARE_DIR/functions
. $SHARE_DIR/communication

DETECT_DIR=$SHARE_DIR/detect

test_one()
{
	rm -f $HOME/components.xml
	echo -n 'Detecting USB'
	. $DETECT_DIR/usb
	echo_success

	export COMPUTER_ID=`xmlstarlet sel -t -v "list/component[vendor='Tennex Systems Ltd.']/serial" <$HOME/components.xml | sed 's/^00*//';`
	echo COMPUTER_ID=$COMPUTER_ID

	submit_components $HOME/components.xml
	rm -f $HOME/components.xml

	set_profile `cat $HOME/set_profile`

	plan_test_script
	sed -i 's/^PLANNER=1 /export PLANNER=1 /g; s/ run_test \(.*\)$/ \&\& run_test \1 || return 1/g;' $HOME/test_script 
	. $HOME/test_script
}

while true; do
	exec 3>&1
	value=`dialog --item-help --nocancel --backtitle 'Inquisitor Standalone' \
	        --title 'Choose an profile' --menu '' \
	        10 60 4 \
		'4' 'Full testing' '' \
		'2' 'Fast testing' '' \
		'3' 'USB presence only' '' \
		'Quit' 'Quit' '' \
	2>&1 1>&3`
	retval=$?
	exec 3>&-

	clear

	case $retval in
	0)
		;;
	1)
		exit 0
		;;
	255)
		if test -n "$value" ; then
			echo "$value"
		else
			continue # ESC pressed
		fi
		;;
	esac

	case "$value" in
	4|2|3)
		echo $value >$HOME/set_profile
		test_one
		echo
		echo 'Press ENTER to return to main menu'
		read L
		;;
	Quit)
		exit 0
		;;
	esac
done
