#!/bin/sh

. _inq-config-global
. $SHARE_DIR/functions
. $SHARE_DIR/communication

[ -n "$COMPUTER_ID" ] || COMPUTER_ID=`inq-self-id`
if ! [ -n "$COMPUTER_ID" ]; then
	echo_failure 'Self-identification failed'
	exit 1
else
	export COMPUTER_ID
fi

for I in $SHARE_DIR/software-detect/*; do
	echo -n "Detecting `basename $I`"
	. $I
	echo_success
done
