#!/bin/sh -e

. @@ETC_DIR@@/global
. $SHARE_DIR/functions
. $SHARE_DIR/communication

# ===========================================================================
# Detects
# ===========================================================================

echo 'Starting detects'
inq-detect
echo 'Detects finished'

# ===========================================================================
# Self-identification
# ===========================================================================

echo 'Starting self-identification'
# Try various methods for self-id, stop after successful one
COMPUTER_ID=
for I in $SHARE_DIR/self-id/*; do
	echo -n "Trying self-id using $I"
	. $I
	if [ -n "$COMPUTER_ID" ]; then
		echo_success
		break
	else
		echo_failure
	fi
done
[ -n "$COMPUTER_ID" ] || fatal_failure 'Self-identification'
export COMPUTER_ID

# Reporting IP-address to the server
publish_my_ip || fatal_failure 'IP-address update'

# ===========================================================================
# Start watchdog, if available
# ===========================================================================

watchdog_start

# ===========================================================================
# Submit configuration by REST
# ===========================================================================

submit_components $HOME/components.xml

# ===========================================================================
# Starting monitorings
# ===========================================================================

echo 'Starting monitorings'
for I in $SHARE_DIR/monitoring/*; do
	echo -n "Starting `basename $I`"
	monitoring_start `basename $I`
	echo_success
done
echo 'Monitorings were started'

# ===========================================================================
# Starting software detects
# ===========================================================================

echo 'Starting software detects'
inq-software-detect
echo 'Software detects finished'

# ===========================================================================
# Run all tests
# ===========================================================================

plan_test_script
. $HOME/test_script

# We completed all tests
echo "Testing finished"
testing_finished
