#!/bin/sh -e

. /etc/inquisitor/global
. $SHARE_DIR/functions
. $SHARE_DIR/communication
[ -r $SHARE_DIR/init ] && . $SHARE_DIR/init

# ===========================================================================
# Detects
# ===========================================================================

echo 'Starting detects'
for I in $SHARE_DIR/detect/*; do
	echo -n "Detecting `basename $I`"
	. $I
	echo_success
done
echo 'Detects finished'

# ===========================================================================
# Self-identification
# ===========================================================================

echo 'Starting self-identification'
# Try various methods for self-id, stop after successful one
COMPUTER_ID=
for I in $SHARE_DIR/self-id/*; do
	echo -n "Trying self-id using $I"
	. $I
	if [ -n "$COMPUTER_ID" ]; then
		echo_success
		break
	else
		echo_failure
	fi
done
[ -n "$COMPUTER_ID" ] || fatal_failure 'Self-identification'

# Start watchdog, if available
watchdog_start

# ===========================================================================
# Submit configuration by REST
# ===========================================================================

submit_components $HOME/components.xml

#ifdef WATCHDOG
# ===========================================================================
# Set up watchdog
# ===========================================================================

#watchdog &
#IP_ADDRESS=`/sbin/ifconfig eth0 | grep 'inet addr:' | sed 's/^.*:\(.*\)  Bcast.*$/\1/;'`
#ssh $TESTER watchdog-command.rb --add "$MANUFACTURER" "$PRODUCT_NAME" "$SERIAL" "$IP_ADDRESS"
#success "Watchdog of $IP_ADDRESS started"
#endif

# ===========================================================================
# Run all tests
# ===========================================================================

echo -n "Planning tests with"
inq-planner $ETC_DIR/tests/$PROFILE.xml >~/testscript || test_failed_file 'Failed to make a test plan'
echo_success

# Run generated testscript
success "Generated test script... Running..."
. ~/testscript


bash
