#!/bin/sh

PUBLISH_DIR=$HOME/publish

# Set up null communications (only local storage of files)
init_communication()
{
	mkdir -p $PUBLISH_DIR
}

# Store file into publish directory for latter packaging
publish()
{
	cp "$1" "$PUBLISH_DIR/`basename $1`"
}

finalize()
{
	dialog --clear --yesno "Insert USB Flash" 5 40
	if [ $? = 0 ]; then
		sleep 15
		echo -n "Mount USB Flash:"
		mount /media/usbdisk >/dev/null 2>&1 && echo_success || echo_failure
		echo
		if mount | grep -q "/media/usbdisk"; then
			pushd ~/
				tar -cjf /media/usbdisk/`cat ~/old-full-serial | tr "/" "."`-`cat ~/publish/PROFILE`.tar.bz2 publish
			popd
			echo -n "Unmount USB Flash:"
			umount /media/usbdisk >/dev/null 2>&1 && echo_success || echo_failure
			echo
		fi
	fi

}
