#!/bin/sh

get_id_by_macs()
{
	MACS=$1
	if Z=`curl -sf "http://$SERVER/computers/identify?macs=$MACS"`; then
		echo "$Z" | grep '<id' | sed 's/^.*id [^>]*>\s*\([0-9]\+\)\s*<\/\s*id.*$/\1/' 
	fi
}

test_stage_advance()
{
	STAGE=$1
	EVENT=$2
	COMMENT=$3
	curl -sf "http://$SERVER/computers/advance/$COMPUTER_ID.xml?stage=$STAGE&event=$EVENT&comment=$COMMENT"
}

test_stage_progress()
{
	COMPLETE=$1
	TOTAL=$2
	curl -sf "http://$SERVER/computers/progress/$COMPUTER_ID.xml?complete=$COMPLETE&total=$TOTAL"
}

submit_configuration()
{
	FILENAME=$1
	curl -f --data list=\""`cat $FILENAME `"\" -X POST "http://$SERVER/computers/submit_components/$COMPUTER_ID.xml"
}

watchdog()
{
	while true; do
		curl -f http://$SERVER/computers/watchdog/$COMPUTER_ID || echo 'Watchdog ping failed!'
		sleep $[45 + $RANDOM % 15]
	done
}
