#!/bin/sh -ef
# NAME=bonnie
# DESCRIPTION=Bonnie HDD performance benchmark
# VAR=BONNIE_SIZE:int:100:Testing file size in MiB

. /usr/share/inquisitor/functions-benchmark

RESULT_FILE=`mktemp /tmp/benchmark_bonnie.XXXXX`
SCRATCH_DIRECTORY="${RESULT_FILE}_scratch"
mkdir -p $SCRATCH_DIRECTORY

get_drives_list()
{
	DRIVES_LIST=`ls -1 /sys/block/ | grep -v '[0-9]$'`
	DRIVES_QUANTITY=`ls -1 /sys/block/ | grep -v '[0-9]$' | wc -l`
}

perform_benchmark()
{
	DRIVE=$1
	DRIVE_NUMBER=$2

	mke2fs -m0 -F /dev/$DRIVE >/dev/null 2>/dev/null
	mount /dev/$DRIVE $SCRATCH_DIRECTORY

	bonnie++ -u root -d $SCRATCH_DIRECTORY -s $BONNIE_SIZE -n 1 -m benchmark > ${RESULT_FILE}_tmp
	echo -n "hdd"${DRIVE_NUMBER}"="`cat ${RESULT_FILE}_tmp | sed -n '$p' | sed 's/^benchmark,//'`\& >> $RESULT_FILE

	umount $SCRATCH_DIRECTORY
}

clean_up_after_benchmark()
{
	rm -f $RESULT_FILE
	rm -f ${RESULT_FILE}_tmp
	rmdir $SCRATCH_DIRECTORY
}

get_drives_list
benchmark_started

BENCHED_DRIVES=0
for i in $DRIVES_LIST; do
	perform_benchmark $i $BENCHED_DRIVES
	BENCHED_DRIVES=$[ $BENCHED_DRIVES + 1 ]
done

benchmark_finished `cat $RESULT_FILE`
clean_up_after_benchmark
