#!/bin/sh -ef
# NAME=bonnie
# DESCRIPTION=Bonnie HDD performance benchmark
# VAR=BONNIE_SIZE:int:100:Testing file size in MiB

. /usr/share/inquisitor/functions-benchmark

RESULT_FILE=`mktemp /tmp/benchmark_bonnie.XXXXX`

get_drives_list()
{
	DRIVES_LIST=`ls -1 /sys/block/ | grep -v '[0-9]$'`
	DRIVES_QUANTITY=`ls -1 /sys/block/ | grep -v '[0-9]$' | wc -l`
}

perform_benchmark()
{
	DRIVE=$1
	DRIVE_NUMBER=$2

	./additional/bonnie -s $BONNIE_SIZE > ${RESULT_FILE}_tmp
	echo -n "hdd"${DRIVE_NUMBER}"="`cat ${RESULT_FILE}_tmp | sed -n '$p' | sed 's/^ *[0-9]* *// ; s/ /,/g ; s/,,/,/g'`\& >> $RESULT_FILE
}

clean_up_after_benchmark()
{
	rm -f $RESULT_FILE
	rm -f ${RESULT_FILE}_tmp
}

get_drives_list
benchmark_started

BENCHED_DRIVES=0
for i in $DRIVES_LIST; do
	perform_benchmark $i $BENCHED_DRIVES
	BENCHED_DRIVES=$[ $BENCHED_DRIVES + 1 ]
done

benchmark_finished `cat $RESULT_FILE`
clean_up_after_benchmark

#bonnie's example output:
#              -------Sequential Output-------- ---Sequential Input-- --Random--
#              -Per Char- --Block--- -Rewrite-- -Per Char- --Block--- --Seeks---
#Machine    MB K/sec %CPU K/sec %CPU K/sec %CPU K/sec %CPU K/sec %CPU  /sec %CPU
#          100 48158 91.9 56546 10.4 54308  9.6 66496 98.9 1405820 84.0 69145.5 99.4
#
#after parsing:
#48158,91.9,56546,10.4,54308,9.6,66496,98.9,1405820,84.0,69145.5,99.4
