#!/bin/sh -f
# NAME=bonnie
# DESCRIPTION=Bonnie HDD performance benchmark
# DESTROYS_HDD=Y
# POWEROFF_DURING_TEST=N
# VERSION=0.1
# VAR=BONNIE_SIZE:int:100:Testing file size in MiB

. /usr/share/inquisitor/functions-test

RESULT_FILE=`mktemp`
SCRATCH_DIRECTORY="${RESULT_FILE}_scratch"
mkdir -p $SCRATCH_DIRECTORY

get_drives_list()
{
	DRIVES_LIST=`ls -1 /sys/block/ | grep -v '[0-9]$'`
	DRIVES_QUANTITY=`ls -1 /sys/block/ | grep -v '[0-9]$' | wc -l`
}

perform_benchmark()
{
	DRIVE=$1
	DRIVE_NUMBER=$2

	mke2fs -m0 -F /dev/$DRIVE >/dev/null 2>&1
	mount /dev/$DRIVE $SCRATCH_DIRECTORY

	bonnie++ -u root -d $SCRATCH_DIRECTORY -s $BONNIE_SIZE \
		-n 1 -m benchmark > ${RESULT_FILE}_tmp 2>&1
	echo -n "hdd"${DRIVE_NUMBER}"="`sed -n '$p' < ${RESULT_FILE}_tmp | \
		sed 's/^benchmark,//;s/+//g;s/,,//g'`\& >> $RESULT_FILE

	umount $SCRATCH_DIRECTORY
}

clean_up_after_benchmark()
{
	rm -f $RESULT_FILE
	rm -f ${RESULT_FILE}_tmp
	rmdir $SCRATCH_DIRECTORY
}

get_drives_list
test_started 1

BENCHED_DRIVES=0
for i in "$DRIVES_LIST"; do
	perform_benchmark $i $BENCHED_DRIVES
	BENCHED_DRIVES=$[ $BENCHED_DRIVES + 1 ]
done

test_succeeded `cat $RESULT_FILE`
clean_up_after_benchmark
