#!/bin/sh
# NAME=CPU benchmark
# DESCRIPTION=Benchmarks CPU
# DESTROYS_HDD=N

. /usr/share/inquisitor/functions-test

time -o ~/cpubench.log mencoder -ovc lavc -lavcopts vcodec=mpeg4 -oac mp3lame -lameopts vbr=3 -o /dev/null $LIB_DIR/movie.avi
publish ~/cpubench.log

test_ok_file
