#!/bin/sh -ef
# NAME=dhrystone
# DESCRIPTION=Dhrystone integer calculations benchmark
# VAR=DHRYSTONE_DURATION:int:30:Benchmark duration (sec)
# VAR=DHRYSTONE_CHECKTIME:int:50:Time between checks of alive benchmarks

. /usr/share/inquisitor/functions-benchmark

RESULT_FILE=`mktemp /tmp/benchmark_dhrystone.XXXXX`

detect_cpu_quantity()
{
	CPU_QUANTITY=`cat /proc/cpuinfo | grep processor | wc -l`
}

start_benchmarking()
{
	for i in `seq 1 $CPU_QUANTITY`; do
		dhrystone $DHRYSTONE_DURATION 2>&1 | awk '{print $1}' > ${RESULT_FILE}${i} &
	done
}

parse_results()
{
	for i in `seq 1 $CPU_QUANTITY`; do
		echo -n "cpu"${i}"="`cat ${RESULT_FILE}${i}`\& >> ${RESULT_FILE}_parsed
	done
}

clean_up_after_benchmark()
{
	for i in `seq 1 $CPU_QUANTITY`; do
		rm -f ${RESULT_FILE}${i}
	done
	rm -f ${RESULT_FILE}_parsed
}

detect_cpu_quantity
start_benchmarking

benchmark_started

while true; do
	sleep $DHRYSTONE_CHECKTIME
	
	ps a | grep dhrystone > /dev/null
	if (( $? == 0 )); then
		parse_results
		break
	fi
done

benchmark_finished `cat ${RESULT_FILE}_parsed`
clean_up_after_benchmark
