#!/bin/sh -f
# NAME=dhrystone
# DESCRIPTION=Dhrystone integer calculations benchmark
# DESTROYS_HDD=N
# POWEROFF_DURING_TEST=N
# VERSION=0.1
# VAR=DHRYSTONE_DURATION:int:30:Benchmark duration (sec)
# VAR=DHRYSTONE_CHECKTIME:int:50:Time between checks of alive benchmarks

. /usr/share/inquisitor/functions-test

RESULT_FILE=`mktemp`

detect_cpu_quantity()
{
	CPU_QUANTITY=`grep processor /proc/cpuinfo | wc -l`
}

start_benchmarking()
{
	for i in `seq 1 $CPU_QUANTITY`; do
		dhrystone $DHRYSTONE_DURATION 2>&1 | awk '{print $1}' > \
			${RESULT_FILE}${i} &
		echo $$ > ~/dhrystone$i.pid
	done
}

parse_results()
{
	for i in `seq 1 $CPU_QUANTITY`; do
		echo -n "cpu"${i}"="`cat ${RESULT_FILE}${i}`\& >> \
			${RESULT_FILE}_parsed
	done
}

clean_up_after_benchmark()
{
	for i in `seq 1 $CPU_QUANTITY`; do
		rm -f ${RESULT_FILE}${i}
	done
	rm -f ${RESULT_FILE}_parsed
}

detect_cpu_quantity
start_benchmarking

test_started 1

while true; do
	sleep $DHRYSTONE_CHECKTIME
	
	ALIVE=0
	for i in `seq 1 $CPU_QUANTITY`; do
		(( `ps \`cat ~/dhrystone$i.pid\` | wc -l` == 2 )) && \
			$[$ALIVE=$ALIVE + 1]
	done
	if (( ALIVE == 0 )); then
		parse_results
		break
	fi
done

test_succeeded `cat ${RESULT_FILE}_parsed`
clean_up_after_benchmark
