#!/bin/sh -f
# NAME=hdparm
# DESCRIPTION=Hdparm HDD speed benchmark
# DESTROYS_HDD=N
# POWEROFF_DURING_TEST=N
# VERSION=0.1

. /usr/share/inquisitor/functions-test

RESULT_FILE=`mktemp`

get_drives_list()
{
	DRIVES_LIST=`ls -1 /sys/block/ | grep -v '[0-9]$'`
}

perform_benchmark()
{
	DRIVE=$1
	DRIVE_NUMBER=$2

	for i in `seq 1 10`; do
		echo "hdd"${DRIVE_NUMBER}"="`hdparm -t /dev/$DRIVE | grep '^ Timing'`\& >> ${RESULT_FILE}_tmp
	done
	perform_averaging $DRIVE_NUMBER
}

perform_averaging()
{
	DRIVE_NUMBER=$1

	CACHED=`perl -ne 'next if /buffer/;@d=split(" ");$s+=$d[$#d-1];print $s/(++$i),"\n"' <  ${RESULT_FILE}_tmp | sed -n '$p'`
	BUFFERED=`perl -ne 'next if /cache/;@d=split(" ");$s+=$d[$#d-1];print $s/(++$i),"\n"' <  ${RESULT_FILE}_tmp | sed -n '$p'`

	echo -n "hdd"${DRIVE_NUMBER}"="${CACHED}","${BUFFERED}\& >> $RESULT_FILE
}

clean_up_after_benchmark()
{
	rm -f $RESULT_FILE
}

get_drives_list
test_started 1

BENCHED_DRIVES=0
for i in "$DRIVES_LIST"; do
	perform_benchmark $i $BENCHED_DRIVES
	BENCHED_DRIVES=$[ $BENCHED_DRIVES + 1 ]
done

test_succeeded `cat $RESULT_FILE`
clean_up_after_benchmark
