#!/bin/sh -f
# NAME=hdparm
# DESCRIPTION=Hdparm HDD speed benchmark
# DESTROYS_HDD=false
# POWEROFF_DURING_TEST=false
# VERSION=0.1

. /usr/share/inquisitor/functions-test

RESULT_FILE=`mktemp`

perform_benchmark()
{
	DRIVE=$1
	DRIVE_NUMBER=$2

	for i in `seq 1 10`; do
		echo "hdd"${DRIVE_NUMBER}"="`hdparm -t /dev/$DRIVE | \
			grep '^ Timing'`\& >> ${RESULT_FILE}_tmp
	done
	perform_averaging $DRIVE_NUMBER
}

perform_averaging()
{
	DRIVE_NUMBER=$1

	CACHED=`perl -e '@l=map{@d=split;@d[$#d-1] if /cache/}<>;for(@l){$s+=$_;$i++ if $_};print $s/$i' < ${RESULT_FILE}_tmp`
	BUFFERED=`perl -e '@l=map{@d=split;@d[$#d-1] if /buffer/}<>;for(@l){$s+=$_;$i++ if $_};print $s/$i' < ${RESULT_FILE}_tmp`

	echo -n "hdd"${DRIVE_NUMBER}"="${CACHED}","${BUFFERED}\& >> $RESULT_FILE
}

clean_up_after_benchmark()
{
	rm -f $RESULT_FILE
}

get_drives_list
test_started 1

BENCHED_DRIVES=0
for i in `get_odds_list`; do
	perform_benchmark $i $BENCHED_DRIVES
	BENCHED_DRIVES=$[ $BENCHED_DRIVES + 1 ]
done

test_succeeded `cat $RESULT_FILE`
clean_up_after_benchmark
