#!/bin/sh -ef
# NAME=Mencoder
# DESCRIPTION=Mencoder encoding time benchmark
# DESTROYS_HDD=false
# POWEROFF_DURING_TEST=false
# VERSION=0.1
# TAGS=benchmark,cpu,stress
# VAR=ENCODE_OPTIONS:string:-ovc lavc -lavcopts vcodec=mpeg4 -oac mp3lame -lameopts vbr=3:Encoding options
# VAR=FILE_TO_ENCODE:string:/usr/share/inquisitor/movie.avi:Path to file need to be encoded

. /usr/share/inquisitor/functions-test

RESULT_FILE=`mktemp`

test_started 1

time -o $RESULT_FILE mencoder $ENCODE_OPTIONS \
	-o /dev/null $FILE_TO_ENCODE

RESULT=`awk '{print $1,$2}' < $RESULT_FILE | \
	sed -n 's/user//;s/system//;s/ /,/;1p'`

test_succeeded "result=${RESULT}"
