#!/bin/sh -f
# NAME=stream
# DESCRIPTION=STREAM memory throughput benchmark
# DESTROYS_HDD=false
# POWEROFF_DURING_TEST=false
# VERSION=0.1

. /usr/share/inquisitor/functions-test

test_started 1

RESULT=`stream-mem | grep -A 4 Function | \
	perl -e '@l=map{split}<STDIN>;print join ",",$l[10],$l[15],$l[20],$l[25]'`

test_succeeded "result=${RESULT}"
