#!/bin/sh -f
# NAME=whetstone
# DESCRIPTION=Whetstone floating-point calculations benchmark
# DESTROYS_HDD=false
# POWEROFF_DURING_TEST=false
# VERSION=0.1
# VAR=WHETSTONE_LOOPS:int:20000:Loop count
# VAR=WHETSTONE_CHECKTIME:int:60:Time between checks of alive benchmarks

. /usr/share/inquisitor/functions-test

RESULT_FILE=`mktemp`

detect_cpu_quantity()
{
	CPU_QUANTITY=`grep processor /proc/cpuinfo | wc -l`
}

start_benchmarking()
{
	for i in `seq 1 $CPU_QUANTITY`; do
		whetstone $WHETSTONE_LOOPS | grep Whetstones | \
			awk '{print $6}' > ${RESULT_FILE}${i} &
		echo $$ > ~/whetstone$i.pid
	done
}

parse_results()
{
	for i in `seq 1 $CPU_QUANTITY`; do
		echo -n "cpu"${i}"="`cat ${RESULT_FILE}${i}`\& >> \
			${RESULT_FILE}_parsed
	done
}

clean_up_after_benchmark()
{
	for i in `seq 1 $CPU_QUANTITY`; do
		rm -f ${RESULT_FILE}${i}
	done
	rm -f ${RESULT_FILE}_parsed
}

detect_cpu_quantity
start_benchmarking

test_started 1

while true; do
	sleep $WHETSTONE_CHECKTIME
	
	ALIVE=0
	for i in `seq 1 $CPU_QUANTITY`; do
		(( `ps \`cat ~/whetstone$i.pid\` | wc -l` == 2 )) && \
			ALIVE=$(( $ALIVE + 1 ))
	done
	if [ $ALIVE -eq 0 ]; then
		parse_results
		break
	fi
done

test_succeeded `cat ${RESULT_FILE}_parsed`
clean_up_after_benchmark
