#!/bin/sh -ef
# NAME=CPU
# DESCRIPTION=CPU burn-in testing
# DESTROYS_HDD=N
# IS_INTERACTIVE=N
# POWEROFF_DURING_TEST=N
# VAR=CPU_TEST_TIME:int:Total time of CPU testing
# VAR=CPU_LOG_TIME:int:Time between progress updates

. /usr/share/inquisitor/functions

[ -z "$TEST_NAME" ] && TEST_NAME=`basename $0`
CPU_TEST_TIME=3600
CPU_LOG_TIME=30

detect_burn_program()
{
	CPU_VENDOR=`cat /proc/cpuinfo | grep vendor_id | awk '{print $3}' | sed '2,$d'`

	case $CPU_VENDOR in
	AuthenticAMD)
		BURN_PROGRAM="burnK7"
		;;
	*)
		BURN_PROGRAM="burnP6"
		;;
	esac
}

detect_cpu_quantity()
{
	CPU_QUANTITY=`cat /proc/cpuinfo | grep processor | wc -l`
}

start_burn()
{
	for i in `seq 1 $CPU_QUANTITY`;
	do
		$BURN_PROGRAM &
		echo $! >~/cpuburn$i.pid
	done
}

stop_burn()
{
	for i in `seq 1 $CPU_QUANTITY`;
	do
		killbypid cpuburn$i
	done
}

detect_burn_program
detect_cpu_quantity
start_burn
test_started $CPU_TEST_TIME

LASTTIME=0
START=`date "+%s"`
while true; do
	sleep $CPU_LOG_TIME
	TIME=`date "+%s"`
	if (( TIME - START > CPU_TEST_TIME )); then 
		stop_burn
		test_succeeded
		break
	else
		test_progress $TIME $CPU_TEST_TIME
	fi
done
