#!/bin/sh -e
# NAME=Stress_flash
# DESCRIPTION=Stress test for flash
# DESTROYS_HDD=Y
# IS_INTERACTIVE=N
# POWEROFF_DURING_TEST=N
# VAR=STRESS_FLASH_SIZE_LIMIT_MB:int:Everything that is less than this amount (MB) is an IDE flash

. /usr/share/inquisitor/functions-test

rmmod pata-amd || echo WARNING: no pata-amd
sleep 10
modprobe ide-generic
sleep 10

# Same in blocks (1 block = 512 bytes)
FLASH_SIZE_LIMIT=$[$STRESS_FLASH_SIZE_LIMIT_MB * 1024 * 2]

for P in /sys/block/*; do
	I=`basename $P`
	echo "$I" | egrep -q '[0-9]' && continue
	echo -n "Querying device $I... "
	grep -q "$I" /proc/partitions || continue
	SIZE=`cat /sys/block/$I/size`
	if [ "$SIZE" -lt "$FLASH_SIZE_LIMIT" ]; then
		echo "found IDE flash!"
		publish_msg "Testing flash drive $I"
		badblocks -svw /dev/$I || ( echo "failed IDE flash test on $I"; publish_msg "Failed IDE flash test on $I")
	else
		echo "not an IDE flash ($SIZE blocks)"
	fi
done

test_success
