#!/bin/sh
# NAME=Load
# DESCRIPTION=Loading stress test
# DESTROYS_HDD=N
# IS_INTERACTIVE=N
# POWEROFF_DURING_TEST=N
# VAR=LOAD_JOBS:int:16:Number of parallely running jobs during compile
# VAR=LOAD_TEST_TIME:int:3600:Total time of Load testing
# VAR=LOAD_LOG_TIME:int:60:Time between progress updates

. /usr/share/inquisitor/functions-test

LOAD_ROOT=`mktemp -d /tmp/load_test.XXXXX`
LOAD_TREE="/usr/share/inquisitor/linux-2.6.15_stress"

before_load()
{
	cd "$LOAD_ROOT"
	TREE_NAME=`basename "$LOAD_TREE"`
	tar xzf "${LOAD_TREE}.tar.gz"
	cd "$TREE_NAME"

	#is it linux source?
	if echo "$TREE_NAME" | grep '^linux' ; then
		find | xargs touch
		touch .config 
		touch include/linux/autoconf.h
	fi
}

prepare_ramdrive()
{
	RAMDRIVE=$1

	#check if we need to load the ramdrive module
	lsmod | grep -w rd 2>/dev/null >/dev/null || modprobe rd

	#determine default ramdrive if none was specified in params
	[ -z "$RAMDRIVE" ] && RAMDRIVE=/dev/`ls /sys/block/ | grep 'ram[0-9]' | sort | head -n 1`

	prepare_partition $RAMDRIVE
}

remove_ramdrive()
{
	RAMDRIVE=$1
        [ -z "$RAMDRIVE" ] && RAMDRIVE=/dev/`ls /sys/block/ | grep 'ram[0-9]' | sort | head -n 1`
	remove_partition "$RAMDRIVE"
}


remove_partition()
{
	DRIVE=$1
	umount "$DRIVE" 2>/dev/null
}

prepare_partition()
{
	DEVICE=$1
	mke2fs -m0 -F "$DEVICE" || test_failed
	[ ! -e "${LOAD_ROOT}/${DEVICE}" ] && mkdir -p "${LOAD_ROOT}/${DEVICE}"
	mount "$DEVICE" "${LOAD_ROOT}/${DEVICE}" 2>/dev/null || test_failed
}

before_load
prepare_ramdrive

LASTTIME=0
START=`date "+%s"`
test_started $LOAD_TEST_TIME

while true; do 
	TIME=`date "+%s"`

	if (( TIME - START > LOAD_TEST_TIME )); then 
		remove_ramdrive
		test_succeeded
		break
	else
		test_progress $[$TIME - $START] $LOAD_TEST_TIME
	fi

	make clean >/dev/null 2>/dev/null && make -j $JOBS fs >/dev/null 2>/dev/null || test_failed
done
