#!/bin/sh
# NAME=odd_read
# DESCRIPTION=Optical Disc Drive read test
# DESTROYS_HDD=N
# IS_INTERACTIVE=Y
# POWEROFF_DURING_TEST=N
# VERSION=0.1
# VAR=ODD_TEST_IMAGE:str:/usr/share/inquisitor/testimage.iso:Default image for comparison
# VAR=ODD_TEST_IMAGE_BLOCKS:int:332800:This images size in blocks (2048 bytes each)
# VAR=ODD_MESH_POINTS:int:1024:Points for meshes for monitoring drive's speed

. /usr/share/inquisitor/functions-test

ODD_IMAGE=`mktemp`
RESULT_FILE=`mktemp`

detect_odd_quantity()
{
	ODD_QUANTITY=`hal-find-by-capability --capability storage.cdrom | wc -l`
}

test_odd()
{
	ODD=$1

	readcd -v dev=$ODD f=$ODD_IMAGE sectors=0-$ODD_TEST_IMAGE_BLOCKS meshpoints=$ODD_MESH_POINTS 2>&1 >$RESULT_FILE
	[ ! -s $ODD_IMAGE ] && dd if=$ODD of=$ODD_IMAGE bs=2048 count=$ODD_TEST_IMAGE_BLOCKS >/dev/null 2>&1

	diff $ODD_TEST_IMAGE $ODD_IMAGE >/dev/null 2>&1 || return 1
	return 0
}

interactive()
{
	ODD=$1
	NON_PASSED=1

	while ( [ $NON_PASSED ] ); do
		eject $ODD
		echo -n "Drive $[ $TESTED_QUANTITY + 1]:Either press Y and insert media for testing, or N if you want to finish test: "
		read foobar

		[ $foobar = "N" ] && test_failed

		test_odd $ODD

		if (( $? == 0 )); then
			echo "Drive test passed"
			TESTED_QUANTITY=$[ $TESTED_QUANTITY + 1 ]
			test_progress $TESTED_QUANTITY $ODD_QUANTITY
			NON_PASSED=0

			generate_speed_results
		else
			echo "Drive test failed!"
		fi
	done
}

remove_test_image()
{
	rm -f $ODD_IMAGE
}

generate_speed_results()
{
	FOO=`cat $RESULT | grep addr: $RESULT_FILE | awk '{OFS=",";print $5,$6}' | sed '$d; s/$/\;/'`
	BAR=""
	for i in $FOO; do
		BAR=${BAR}$i
	done

	#here will be call to publish this monitoring results
}

detect_odd_quantity
TESTED_QUANTITY=0
test_started $ODD_QUANTITY

for i in `hal-find-by-capability --capability storage.cdrom`; do
	interactive `hal-device $i | grep access_control.file | awk '{print $3}' | sed "s/'//g"`
done

remove_test_image
test_succeeded
