#!/bin/sh
# NAME=Iozone
# DESCRIPTION=Detect IOzone benchmark version.

version=`iozone -version | sed -n 's/^ *Version \$\(Revision:.*\)\$$/\1/p'`
arch=`executable_arch tar`

add_software_component iozone "$arch" "$version"
