#!/bin/sh
# NAME=SpeexEnc
# DESCRIPTION=Detect Speex encoder version.

version=`speexenc --version | sed -n 's/^.*version \([^ ]*\) .*$/\1/p'`
arch=`executable_arch speexenc`

add_software_component speexenc "$arch" "$version"
